version: '3.7'
services:
  redis:
    image: "redis:alpine"
    restart: always
    container_name: redis
    command: redis-server
    ports:
      - 6379:6379
  web:
    build: .
    command:  bash -c "python3 /usr/src/sereja/manage.py migrate --noinput && python3 /usr/src/sereja/manage.py loaddata db.json && gunicorn sereja.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/static
      - .:/media
    expose:
      - 8000
    env_file:
      - ./.env.dev
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=ser
      - POSTGRES_PASSWORD=01021979a
      - POSTGRES_DB=ser_db
      - POSTGRES_HOST=db
  nginx:
    build: ./nginx
    volumes:
      - .:/static
      - .:/media
    ports:
      - 1337:80
    depends_on:
      - web
  celery:
    build: .
    container_name: celery
    command: celery -A sereja worker -l INFO
    volumes:
      - .:/usr/src/sereja
    env_file:
      - ./.env.dev
    depends_on:
      - web
      - redis
  celery_beat:
    build: .
    container_name: celery_beat
    command: celery -A sereja beat -l INFO
    volumes:
      - .:/usr/src/sereja
    env_file:
      - ./.env.dev
    depends_on:
      - web
      - redis

volumes:
  postgres_data:
