# Generated by Django 3.1.1 on 2021-12-02 13:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.PositiveIntegerField(db_index=True, default=0, verbose_name='summa')),
                ('kind', models.CharField(choices=[('Ремонт ПК', 'Ремонт ПК'), ('Сборка', 'Сборка'), ('Обслуживание', 'Обслуживание')], db_index=True, default='Сборка', max_length=50, verbose_name='kind')),
                ('sloznostPK', models.CharField(choices=[('простой', 'простой'), ('обычный', 'обычный'), ('сложный', 'сложный'), ('ультра', 'ультра')], db_index=True, default='простой', max_length=50, verbose_name='sloznostPK')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['summa'],
            },
        ),
        migrations.AddField(
            model_name='managers',
            name='remontnik',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='managers',
            name='sborsik',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bids',
            name='ID',
            field=models.PositiveIntegerField(unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='istocnikZakaza',
            field=models.CharField(choices=[('КОРЗИНА', 'КОРЗИНА'), ('Rozetka', 'Rozetka'), ('Алло', 'Алло'), ('Телефон_Чат', 'Телефон_Чат'), ('Офис', 'Офис'), ('Другой', 'Другой')], db_index=True, default='Телефон_Чат', max_length=20, verbose_name='istocnikZakaza'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='site',
            field=models.CharField(choices=[('versum', 'versum'), ('itblok', 'itblok')], db_index=True, default='versum', max_length=10, verbose_name='site'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='status',
            field=models.CharField(choices=[('Отправлен', 'Отправлен'), ('Подтверждён', 'Подтверждён'), ('Ожидает деталь', 'Ожидает деталь'), ('Идёт диалог', 'Идёт диалог'), ('Ожидаем оплату', 'Ожидаем оплату'), ('Заказ товара', 'Заказ товара'), ('Идёт сборка', 'Идёт сборка'), ('Дубль', 'Дубль'), ('Выкуплен', 'Выкуплен'), ('Неактуально', 'Неактуально'), ('Ремонт ПК', 'Ремонт ПК'), ('Удален', 'Удален'), ('Отказ', 'Отказ')], db_index=True, default='Идёт диалог', max_length=50, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='bids',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.bids'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='kind',
            field=models.CharField(choices=[('Системный блок', 'Системный блок'), ('ПО', 'ПО'), ('Комплектующие', 'Комплектующие')], db_index=True, default='Системный блок', max_length=100, verbose_name='kind'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='istocnikZakaza',
            field=models.CharField(choices=[('КОРЗИНА', 'КОРЗИНА'), ('Rozetka', 'Rozetka'), ('Алло', 'Алло'), ('Телефон_Чат', 'Телефон_Чат'), ('Офис', 'Офис'), ('Другой', 'Другой')], db_index=True, default='Телефон_Чат', max_length=20, verbose_name='istocnikZakaza'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='kind',
            field=models.CharField(choices=[('Системный блок', 'Системный блок'), ('ПО', 'ПО'), ('Комплектующие', 'Комплектующие')], db_index=True, default='Системный блок', max_length=100, verbose_name='kind'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='site',
            field=models.CharField(choices=[('versum', 'versum'), ('itblok', 'itblok')], db_index=True, default='versum', max_length=10, verbose_name='site'),
        ),
        migrations.CreateModel(
            name='Statistics_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('sborka_count', models.PositiveIntegerField(default=0, verbose_name='otkaz_count')),
                ('remont_count', models.PositiveIntegerField(default=0, verbose_name='positive_count')),
                ('obsluj_count', models.PositiveIntegerField(default=0, verbose_name='positive_count')),
                ('managers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.managers')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.service')),
            ],
            options={
                'verbose_name': 'Statistics_service',
                'verbose_name_plural': 'Statistics_services',
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='managers',
            field=models.ManyToManyField(to='money.Managers'),
        ),
    ]
