# Generated by Django 3.1.1 on 2021-12-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_auto_20211202_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='managers',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='statistics_service',
            name='few_managers',
            field=models.BooleanField(default=False),
        ),
    ]
