# Generated by Django 3.1.1 on 2021-12-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0003_auto_20211206_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='site',
            field=models.CharField(choices=[('versum', 'versum'), ('komputeritblok', 'komputeritblok')], db_index=True, default='versum', max_length=20, verbose_name='site'),
        ),
    ]
