# Generated by Django 3.1.1 on 2021-12-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0005_auto_20211206_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='nalog_na_pribil',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='nalog_na_pribil'),
        ),
        migrations.AddField(
            model_name='bids',
            name='nds',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='nds'),
        ),
    ]
