# Generated by Django 3.1.1 on 2021-12-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0006_auto_20211209_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics_service',
            name='few_managers',
        ),
        migrations.AddField(
            model_name='bids',
            name='few_sborsik',
            field=models.CharField(db_index=True, default='', max_length=100, verbose_name='site'),
        ),
    ]
