# Generated by Django 3.1.1 on 2021-12-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0007_auto_20211213_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='amount',
            field=models.PositiveIntegerField(db_index=True, default=1, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='status',
            field=models.CharField(choices=[('Отправлен', 'Отправлен'), ('Подтверждён', 'Подтверждён'), ('Ожидает деталь', 'Ожидает деталь'), ('Идёт диалог', 'Идёт диалог'), ('Ожидаем оплату', 'Ожидаем оплату'), ('Заказ товара', 'Заказ товара'), ('Идёт сборка', 'Идёт сборка'), ('Дубль', 'Дубль'), ('Выкуплен', 'Выкуплен'), ('Неактуально', 'Неактуально'), ('Ремонт ПК', 'Ремонт ПК'), ('Сервис', 'Сервис'), ('Удален', 'Удален'), ('Отказ', 'Отказ')], db_index=True, default='Идёт диалог', max_length=50, verbose_name='status'),
        ),
    ]
