# Generated by Django 3.1.1 on 2022-01-12 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('money', '0008_auto_20211223_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bids',
            options={'ordering': ['date_ch'], 'permissions': (('only_managers', 'only managers'), ('only_sereja', 'only sereja')), 'verbose_name': 'Bid', 'verbose_name_plural': 'Bids'},
        ),
        migrations.AlterModelOptions(
            name='managers',
            options={'ordering': ['name'], 'permissions': (('only_managers', 'only managers'), ('only_sereja', 'only sereja')), 'verbose_name': 'Manager', 'verbose_name_plural': 'Managers'},
        ),
        migrations.AlterModelOptions(
            name='statistics_service',
            options={'ordering': ['date'], 'permissions': (('only_managers', 'only managers'), ('only_sereja', 'only sereja')), 'verbose_name': 'Statistics_service', 'verbose_name_plural': 'Statistics_services'},
        ),
        migrations.AddField(
            model_name='bids',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='managers',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='statistics_service',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
