# Generated by Django 3.1.1 on 2022-01-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0010_auto_20220112_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['summa'], 'verbose_name': 'Goods', 'verbose_name_plural': 'Goods'},
        ),
        migrations.AlterField(
            model_name='bids',
            name='site',
            field=models.CharField(choices=[('versum', 'versum'), ('komputeritblok', 'komputeritblok'), ('both', 'both')], db_index=True, default='versum', max_length=20, verbose_name='site'),
        ),
    ]
