# Generated by Django 3.1.1 on 2022-01-22 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0011_auto_20220118_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bids_advanced',
            fields=[
            ],
            options={
                'verbose_name': 'Bids_advanced',
                'verbose_name_plural': 'Bidses_advanced',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('money.bids',),
        ),
    ]
