# Generated by Django 3.1.1 on 2022-01-28 12:30

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0014_auto_20220127_1402'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bids',
            managers=[
                ('goods', django.db.models.manager.Manager()),
            ],
        ),
    ]
