# Generated by Django 3.1.1 on 2022-01-28 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0015_auto_20220128_1430'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bids',
            managers=[
            ],
        ),
    ]
