# Generated by Django 3.1.1 on 2022-02-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0016_auto_20220128_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='first_sborsik',
        ),
        migrations.AddField(
            model_name='bids',
            name='few_sborsik',
            field=models.CharField(db_index=True, default='', max_length=100, verbose_name='few_sborsik'),
        ),
    ]
