# Generated by Django 3.1.1 on 2022-02-19 15:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0017_auto_20220217_0652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(db_index=True, default=0, verbose_name='amount')),
                ('discr', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='Статья расходов')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Gross_profit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[('versum', 'versum'), ('itblok', 'itblok')], db_index=True, default='versum', max_length=10, verbose_name='site')),
                ('amount', models.FloatField(db_index=True, default=0, verbose_name='amount')),
                ('quantity', models.PositiveIntegerField(db_index=True, default=0, verbose_name='quantity')),
                ('grossprofit', models.FloatField(db_index=True, default=0, verbose_name='grossprofit')),
                ('rentability', models.FloatField(db_index=True, default=0, verbose_name='rentability')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Gross_profit',
                'verbose_name_plural': 'Gross_profits',
                'ordering': ['date'],
            },
        ),
        migrations.AlterField(
            model_name='statistics_service',
            name='sborka_count',
            field=models.PositiveIntegerField(default=0, verbose_name='sborka_count'),
        ),
    ]
