# Generated by Django 3.1.1 on 2022-02-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0019_koefficient'),
    ]

    operations = [
        migrations.AddField(
            model_name='koefficient',
            name='plan',
            field=models.FloatField(db_index=True, default=0, verbose_name='План'),
        ),
    ]
