# Generated by Django 3.1.1 on 2022-02-22 07:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0020_koefficient_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('plan', models.FloatField(db_index=True, default=0, verbose_name='План')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'ordering': ['date'],
            },
        ),
        migrations.RemoveField(
            model_name='koefficient',
            name='plan',
        ),
        migrations.AddField(
            model_name='expense',
            name='summa',
            field=models.FloatField(db_index=True, default=0, verbose_name='Сумма расходов'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.FloatField(db_index=True, default=0, verbose_name='Расходы по статье'),
        ),
        migrations.AlterField(
            model_name='gross_profit',
            name='site',
            field=models.CharField(choices=[('Versum', 'Versum'), ('IT-Blok', 'IT-Blok'), ('both', 'both')], db_index=True, default='versum', max_length=10, verbose_name='site'),
        ),
        migrations.AlterField(
            model_name='koefficient',
            name='hand',
            field=models.FloatField(db_index=True, default=1.18, verbose_name='Коэффициент'),
        ),
    ]
