# Generated by Django 3.1.1 on 2022-03-09 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('money', '0021_auto_20220222_0933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bids',
            options={'ordering': ['date_ch'], 'permissions': (('only_managers', 'only managers'), ('only_sereja', 'only sereja')), 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='bids_advanced',
            options={'verbose_name': 'Статистика', 'verbose_name_plural': 'Статистика'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['date'], 'verbose_name': 'Расходы', 'verbose_name_plural': 'Расходы'},
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['summa'], 'verbose_name': 'Товар из заявки', 'verbose_name_plural': 'Товары из заявок'},
        ),
        migrations.AlterModelOptions(
            name='gross_profit',
            options={'ordering': ['date'], 'verbose_name': 'Валовая прибыль', 'verbose_name_plural': 'Валовая прибыль'},
        ),
        migrations.AlterModelOptions(
            name='koefficient',
            options={'ordering': ['date'], 'verbose_name': 'Коэффициент', 'verbose_name_plural': 'Коэффициент'},
        ),
        migrations.AlterModelOptions(
            name='managers',
            options={'ordering': ['name'], 'permissions': (('only_managers', 'only managers'), ('only_sereja', 'only sereja')), 'verbose_name': 'Менеджер', 'verbose_name_plural': 'Менеджеры'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['date'], 'verbose_name': 'План', 'verbose_name_plural': 'План'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['summa'], 'verbose_name': 'Сервис', 'verbose_name_plural': 'Сервисы'},
        ),
        migrations.AlterModelOptions(
            name='statistics_bid',
            options={'ordering': ['date'], 'verbose_name': 'Сборщики-ремонтники', 'verbose_name_plural': 'Сборщики-ремонтники'},
        ),
        migrations.AlterModelOptions(
            name='statistics_service',
            options={'ordering': ['managers__name'], 'permissions': (('only_managers', 'only managers'), ('only_sereja', 'only sereja')), 'verbose_name': 'Сборщики-ремонтники', 'verbose_name_plural': 'Сборщики-ремонтники'},
        ),
        migrations.AddField(
            model_name='managers',
            name='super',
            field=models.BooleanField(default=False, verbose_name='Главный менеджер'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='date_ch',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='istocnikZakaza',
            field=models.CharField(choices=[('КОРЗИНА', 'КОРЗИНА'), ('Rozetka', 'Rozetka'), ('Алло', 'Алло'), ('Телефон_Чат', 'Телефон_Чат'), ('Офис', 'Офис'), ('Другой', 'Другой')], db_index=True, default='Телефон_Чат', max_length=20, verbose_name='Исочник заказа'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='managers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='money.managers', verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='nalog_na_pribil',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Налог на прибыль'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='nds',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='НДС'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='site',
            field=models.CharField(choices=[('versum', 'versum'), ('komputeritblok', 'komputeritblok'), ('both', 'both')], db_index=True, default='versum', max_length=20, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='sposobOplaty',
            field=models.CharField(blank=True, choices=[('Другой способ оплаты', 'Другой способ оплаты'), ('Кредит Альфа Банк', 'Кредит Альфа Банк'), ('Оплата на ФОП', 'Оплата на ФОП'), ('Оплата картой Visa/MasterCard', 'Оплата картой Visa/MasterCard'), ('Оплата онлайн-картой (LiqPay)', 'Оплата онлайн-картой (LiqPay)'), ('Безналичный с НДС', 'Безналичный с НДС'), ('На карту', 'На карту'), ('Кредит Монобанк', 'Кредит Монобанк'), ('Готівкою', 'Готівкою')], db_index=True, max_length=100, null=True, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='status',
            field=models.CharField(choices=[('Отправлен', 'Отправлен'), ('Подтверждён', 'Подтверждён'), ('Идёт диалог', 'Идёт диалог'), ('Ожидаем оплату', 'Ожидаем оплату'), ('Заказ товара', 'Заказ товара'), ('Идёт сборка', 'Идёт сборка'), ('Выкуплен', 'Выкуплен'), ('Сервис', 'Сервис'), ('Отказ', 'Отказ')], db_index=True, default='Идёт диалог', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='amount',
            field=models.PositiveIntegerField(db_index=True, default=1, verbose_name='Колличество'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='bids',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.bids', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='discr',
            field=models.TextField(blank=True, db_index=True, max_length=5000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='kind',
            field=models.CharField(choices=[('Системный блок', 'Системный блок'), ('ПО', 'ПО'), ('Комплектующие', 'Комплектующие')], db_index=True, default='Системный блок', max_length=100, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='summa',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='gross_profit',
            name='amount',
            field=models.FloatField(db_index=True, default=0, verbose_name='Оборот'),
        ),
        migrations.AlterField(
            model_name='gross_profit',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='gross_profit',
            name='grossprofit',
            field=models.FloatField(db_index=True, default=0, verbose_name='Прибыль по ПК'),
        ),
        migrations.AlterField(
            model_name='gross_profit',
            name='quantity',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Колличество ПК'),
        ),
        migrations.AlterField(
            model_name='gross_profit',
            name='rentability',
            field=models.FloatField(db_index=True, default=0, verbose_name='Наценка'),
        ),
        migrations.AlterField(
            model_name='gross_profit',
            name='site',
            field=models.CharField(choices=[('Versum', 'Versum'), ('IT-Blok', 'IT-Blok'), ('both', 'both')], db_index=True, default='versum', max_length=10, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Имя для своей страницы '),
        ),
        migrations.AlterField(
            model_name='managers',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='name',
            field=models.CharField(db_index=True, default='somebody', max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='remontnik',
            field=models.BooleanField(default=False, verbose_name='Ремонтник'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='sborsik',
            field=models.BooleanField(default=False, verbose_name='Сборщик'),
        ),
        migrations.AlterField(
            model_name='service',
            name='kind',
            field=models.CharField(choices=[('Ремонт ПК', 'Ремонт ПК'), ('Сборка', 'Сборка'), ('Обслуживание', 'Обслуживание')], db_index=True, default='Сборка', max_length=50, verbose_name='Вид работ'),
        ),
        migrations.AlterField(
            model_name='service',
            name='sloznostPK',
            field=models.CharField(choices=[('простой', 'простой'), ('обычный', 'обычный'), ('сложный', 'сложный'), ('ультра', 'ультра')], db_index=True, default='простой', max_length=50, verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='service',
            name='summa',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Оплата за этот вид работ'),
        ),
        migrations.AlterField(
            model_name='statistics_service',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='statistics_service',
            name='managers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.managers', verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='statistics_service',
            name='obsluj_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол обслуживаний'),
        ),
        migrations.AlterField(
            model_name='statistics_service',
            name='remont_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол ремонтов'),
        ),
        migrations.AlterField(
            model_name='statistics_service',
            name='sborka_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол сборок'),
        ),
        migrations.AlterField(
            model_name='statistics_service',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.service', verbose_name='Вид'),
        ),
    ]
