# Generated by Django 3.1.1 on 2022-03-16 13:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0022_auto_20220309_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='kind',
            field=models.CharField(choices=[('Версум реклама', 'Версум реклама'), ('Версум расстраты текущие', 'Версум расстраты текущие'), ('Ит-Блок расстраты текущие', 'Ит-Блок расстраты текущие'), ('Андрей Мишутин расстраты текущие', 'Андрей Мишутин расстраты текущие'), ('Расстраты на оба проэкта', 'Расстраты на оба проэкта'), ('Ручные поля', 'Ручные поля'), ('Другие растраты', 'Другие растраты')], db_index=True, default='Другие растраты', max_length=100, verbose_name='Вид трат'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='date_ch',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
    ]
