# Generated by Django 3.1.1 on 2022-03-16 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0023_auto_20220316_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense_groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='Группы расходов')),
            ],
            options={
                'verbose_name': 'Группы расходов',
                'verbose_name_plural': 'Группы расходов',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='expense',
            name='kind',
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_groups',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='money.expense_groups', verbose_name='Вид трат'),
        ),
    ]
