# Generated by Django 3.1.1 on 2022-08-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0024_auto_20220316_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managers',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Менеджер'),
        ),
    ]
