# Generated by Django 3.1.1 on 2022-09-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0025_auto_20220824_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='first_sborsik',
            field=models.CharField(db_index=True, default='', max_length=100, verbose_name='first_sborsik'),
        ),
    ]
