# Generated by Django 4.1.6 on 2023-03-13 10:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0027_auto_20221003_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Average_check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('quantity', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ПК план')),
                ('site', models.CharField(choices=[('versum', 'versum'), ('itblok', 'itblok')], db_index=True, default='versum', max_length=20, verbose_name='сайт')),
                ('price', models.FloatField(db_index=True, default=35000.0, verbose_name='Чек')),
                ('hand_check', models.FloatField(db_index=True, default=1500.0, verbose_name='Средние траты')),
                ('plan_check', models.FloatField(db_index=True, default=75000.0, verbose_name='Запланированные траты')),
            ],
            options={
                'verbose_name': 'Средний чек',
                'verbose_name_plural': 'Средний чек',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Ratios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата')),
                ('tax_ratio', models.FloatField(db_index=True, default=0.18, verbose_name='Налог на прибыль')),
                ('itblok_ratio', models.FloatField(db_index=True, default=0.065, verbose_name='Айтиблок_расход_на_один_комп')),
                ('versum_ratio', models.FloatField(db_index=True, default=0.015, verbose_name='Версум_расход_на_один_комп')),
            ],
            options={
                'verbose_name': 'Слежебные коэф',
                'verbose_name_plural': 'Слежебные коэф',
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='site',
            field=models.CharField(choices=[('versum', 'versum'), ('itblok', 'itblok'), ('tenders', 'tenders'), ('others', 'others'), ('both', 'both')], db_index=True, default='versum', max_length=20, verbose_name='сайт'),
        ),
        migrations.AddField(
            model_name='gross_profit',
            name='amountcomponents',
            field=models.FloatField(db_index=True, default=0, verbose_name='Оборот_детали_ПК'),
        ),
        migrations.AddField(
            model_name='gross_profit',
            name='grossprofitcomponents',
            field=models.FloatField(db_index=True, default=0, verbose_name='Прибыль_детали_ПК'),
        ),
        migrations.AddField(
            model_name='gross_profit',
            name='quantity_total',
            field=models.FloatField(db_index=True, default=0, verbose_name='Колличество_ПК_Сумма '),
        ),
        migrations.AddField(
            model_name='gross_profit',
            name='sumProfit',
            field=models.FloatField(db_index=True, default=0, verbose_name='Прибыль_Сумма'),
        ),
        migrations.AddField(
            model_name='gross_profit',
            name='sumSales',
            field=models.FloatField(db_index=True, default=0, verbose_name='Оборот_Сумма'),
        ),
        migrations.AddField(
            model_name='gross_profit',
            name='totalProfit',
            field=models.FloatField(db_index=True, default=0, verbose_name='Прибыль_ПК_Сумма '),
        ),
        migrations.AddField(
            model_name='gross_profit',
            name='totalSales',
            field=models.FloatField(db_index=True, default=0, verbose_name='Оборот_ПК_Сумма '),
        ),
        migrations.AddField(
            model_name='managers',
            name='cash_rate',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Ставка'),
        ),
        migrations.AddField(
            model_name='managers',
            name='cash_rate_already',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Уже получил'),
        ),
        migrations.AddField(
            model_name='plan',
            name='profit_plan',
            field=models.FloatField(db_index=True, default=0, verbose_name='Прибыль расчётная'),
        ),
        migrations.AddField(
            model_name='plan',
            name='site',
            field=models.CharField(choices=[('versum', 'versum'), ('itblok', 'itblok')], db_index=True, default='versum', max_length=20, verbose_name='сайт'),
        ),
        migrations.AddField(
            model_name='plan',
            name='y_plan',
            field=models.FloatField(db_index=True, default=2, verbose_name='Коефициент наценки'),
        ),
        migrations.AddField(
            model_name='plan',
            name='zero_plan',
            field=models.FloatField(db_index=True, default=0, verbose_name='Выход в 0'),
        ),
        migrations.AddField(
            model_name='statistics_service',
            name='km_count',
            field=models.PositiveIntegerField(default=0, verbose_name='km'),
        ),
        migrations.AddField(
            model_name='statistics_service',
            name='site',
            field=models.CharField(choices=[('versum', 'versum'), ('itblok', 'itblok'), ('both', 'both')], db_index=True, default='both', max_length=20, verbose_name='сайт'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='date_ch',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='istocnikZakaza',
            field=models.CharField(choices=[('КОРЗИНА', 'КОРЗИНА'), ('Rozetka', 'Rozetka'), ('Алло', 'Алло'), ('Телефон_Чат', 'Телефон_Чат'), ('Офис', 'Офис'), ('ПК витрина 2%', 'ПК витрина 2%'), ('Инстаграм', 'Инстаграм'), ('Другой', 'Другой')], db_index=True, default='Телефон_Чат', max_length=20, verbose_name='Исочник заказа'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='summa',
            field=models.FloatField(db_index=True, default=0, verbose_name='Сумма расходов сайта'),
        ),
        migrations.AlterField(
            model_name='gross_profit',
            name='amount',
            field=models.FloatField(db_index=True, default=0, verbose_name='Оборот_ПК'),
        ),
        migrations.AlterField(
            model_name='gross_profit',
            name='grossprofit',
            field=models.FloatField(db_index=True, default=0, verbose_name='Прибыль_ПК'),
        ),
        migrations.AlterField(
            model_name='gross_profit',
            name='quantity',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Колличество_ПК'),
        ),
        migrations.AlterField(
            model_name='gross_profit',
            name='site',
            field=models.CharField(choices=[('versum', 'versum'), ('itblok', 'itblok'), ('tenders', 'tenders'), ('others', 'others'), ('both', 'both')], db_index=True, default='versum', max_length=10, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='site',
            field=models.CharField(choices=[('versum', 'versum'), ('itblok', 'itblok'), ('both', 'both')], db_index=True, default='versum', max_length=20, verbose_name='сайт'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='service',
            name='kind',
            field=models.CharField(choices=[('Ремонт ПК', 'Ремонт ПК'), ('Сборка', 'Сборка'), ('Обслуживание', 'Обслуживание'), ('Заказ товара', 'Заказ товара'), ('Глав бух', 'Глав бух'), ('Бухгалтерия', 'Бухгалтерия'), ('Разработка ПО', 'Разработка ПО'), ('Зав склада', 'Зав склада'), ('Курьер', 'Курьер'), ('Оператор 1С', 'Оператор 1С'), ('Офисный менеджер', 'Офисный менеджер'), ('Категорийный менеджер', 'Категорийный менеджер'), ('Офисный комп', 'Офисный комп'), ('Игровой комп', 'Игровой комп')], db_index=True, default='Сборка', max_length=50, verbose_name='Вид работ'),
        ),
        migrations.AlterField(
            model_name='service',
            name='sloznostPK',
            field=models.CharField(choices=[('-', '-'), ('простой', 'простой'), ('обычный', 'обычный'), ('сложный', 'сложный'), ('ультра', 'ультра')], db_index=True, default='простой', max_length=50, verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='service',
            name='summa',
            field=models.FloatField(db_index=True, default=0, verbose_name='Оплата за этот вид работ'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='statistics_bid',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
