from rest_framework import serializers
from .models import *


class CompsSerializer(serializers.Serializer):
    name_computers = serializers.CharField(max_length=300)
    desc_ru = serializers.CharField(max_length=300)
    desc_ukr = serializers.CharField(max_length=300)
    price_computers = serializers.CharField(max_length=300)
    rentability = serializers.CharField(max_length=300)
    cpu = serializers.CharField(source='cpu.name_parts', max_length=300)
    mb = serializers.CharField(source='mb.name_parts', max_length=300)
    ram = serializers.CharField(source='ram.name_parts', max_length=300)
    gpu = serializers.CharField(source='gpu.name_parts', max_length=300)
    hdd = serializers.CharField(source='hdd.name_parts', max_length=300)
    ssd = serializers.CharField(source='ssd.name_parts', max_length=300)
    #ssd2 = serializers.CharField(source='ssd2.name_parts', max_length=300)
    psu = serializers.CharField(source='psu.name_parts', max_length=300)
    case = serializers.CharField(source='case.name_parts', max_length=300)
    cooler = serializers.CharField(source='cooler.name_parts', max_length=300,)
    fan = serializers.CharField(source='fan.name_parts', max_length=300)
    wifi = serializers.CharField(source='wifi.name_parts', max_length=300)
    cables = serializers.CharField(source='cables.name_parts', max_length=300)
    soft = serializers.CharField(source='soft.name_parts', max_length=300)
    mem_num_computers = serializers.CharField(max_length=300)
    video_num_computers = serializers.CharField(max_length=300)
    vent_num_computers = serializers.CharField(max_length=300)
    you_vid = serializers.CharField(max_length=300)
    category = serializers.CharField(source='category.kind_assembly', max_length=300)
    warr_ua = serializers.CharField(max_length=300)
    warr_ru = serializers.CharField(max_length=300)

class Mark_shortSerializer(serializers.Serializer):
    # for trade in
    name_parts = serializers.CharField(max_length=300)
    trade_in_price = serializers.CharField(max_length=300)
    #kind = serializers.CharField(max_length=300)

class CoolerSerializer(serializers.Serializer):
    name = serializers.CharField()
    part_number = serializers.CharField()
    vendor = serializers.CharField()
    price = serializers.CharField()
    rentability = serializers.CharField()
    desc_ukr = serializers.CharField()
    desc_ru = serializers.CharField()
    fan_type_ua = serializers.CharField()
    fan_type_rus = serializers.CharField()
    fan_spd_ua = serializers.CharField()
    fan_spd_rus = serializers.CharField()
    fan_noise_level = serializers.CharField()
    fan_size = serializers.CharField()
    fan_triple_wcs_rus = serializers.CharField()
    fan_triple_wcs_ua = serializers.CharField()
    #depend_to = serializers.CharField()
    #depend_to_type = serializers.CharField()
    cooler_height = serializers.CharField()
    #more = serializers.CharField()
    label = serializers.CharField()
    fan_warr_ua = serializers.CharField(max_length=300)
    fan_warr_ru = serializers.CharField(max_length=300)


class CpuSerializer(serializers.Serializer):
    name = serializers.CharField()
    part_number = serializers.CharField()
    vendor = serializers.CharField()
    price = serializers.CharField()
    rentability = serializers.CharField()
    desc_ukr = serializers.CharField()
    desc_ru = serializers.CharField()
    f_name = serializers.CharField()
    cpu_c_t = serializers.CharField()
    f_cpu_c_t = serializers.CharField()
    cpu_b_f = serializers.CharField()
    cpu_cache = serializers.CharField()
    cpu_i_g_ua = serializers.CharField()
    cpu_i_g_rus = serializers.CharField()
    #more = serializers.CharField()
    #depend_from = serializers.CharField()
    #depend_from_type = serializers.CharField()
    label = serializers.CharField()
    cpu_warr_ua = serializers.CharField(max_length=300)
    cpu_warr_ru = serializers.CharField(max_length=300)


class MbSerializer(serializers.Serializer):
    name = serializers.CharField()
    part_number = serializers.CharField()
    vendor = serializers.CharField()
    #main_category = serializers.CharField()
    price = serializers.CharField()
    rentability = serializers.CharField()
    desc_ukr = serializers.CharField()
    desc_ru = serializers.CharField()
    mb_chipset = serializers.CharField()
    mb_max_ram = serializers.CharField()
    #more = serializers.CharField()
    mb_count_slot = serializers.CharField()
    mb_type_memory = serializers.CharField()
    #depend_to = serializers.CharField()
    #depend_to_type = serializers.CharField()
    #depend_from = serializers.CharField()
    #depend_from_type = serializers.CharField()
    label = serializers.CharField()
    mb_warr_ua = serializers.CharField(max_length=300)
    mb_warr_ru = serializers.CharField(max_length=300)


class RamSerializer(serializers.Serializer):
    name = serializers.CharField()
    part_number = serializers.CharField()
    vendor = serializers.CharField()
    f_name = serializers.CharField()
    price = serializers.CharField()
    rentability = serializers.CharField()
    desc_ukr = serializers.CharField()
    desc_ru = serializers.CharField()
    mem_s = serializers.CharField()
    mem_spd = serializers.CharField()
    mem_l = serializers.CharField()
    #depend_from = serializers.CharField()
    #depend_from_type = serializers.CharField()
    #depend_to = serializers.CharField()
    #depend_to_type = serializers.CharField()
    mem_type = serializers.CharField()
    #more = serializers.CharField()
    label = serializers.CharField()
    mem_warr_ua = serializers.CharField(max_length=300)
    mem_warr_ru = serializers.CharField(max_length=300)


class HddSerializer(serializers.Serializer):
    name = serializers.CharField()
    part_number = serializers.CharField()
    vendor = serializers.CharField()
    f_name = serializers.CharField()
    price = serializers.CharField()
    rentability = serializers.CharField()
    desc_ukr = serializers.CharField()
    desc_ru = serializers.CharField()
    hdd_s = serializers.CharField()
    hdd_spd_ua = serializers.CharField()
    hdd_spd_rus = serializers.CharField()
    hdd_ca = serializers.CharField()
    #more = serializers.CharField()
    label = serializers.CharField()
    hdd_warr_ua = serializers.CharField(max_length=300)
    hdd_warr_ru = serializers.CharField(max_length=300)


class PsuSerializer(serializers.Serializer):
    name = serializers.CharField()
    part_number = serializers.CharField()
    vendor = serializers.CharField()
    price = serializers.CharField()
    rentability = serializers.CharField()
    desc_ukr = serializers.CharField()
    desc_ru = serializers.CharField()
    psu_p = serializers.CharField()
    psu_c = serializers.CharField()
    psu_f = serializers.CharField()
    #more = serializers.CharField()
    label = serializers.CharField()
    psu_warr_ua = serializers.CharField(max_length=300)
    psu_warr_ru = serializers.CharField(max_length=300)


class GpuSerializer(serializers.Serializer):
    name = serializers.CharField()
    part_number = serializers.CharField()
    vendor = serializers.CharField()
    #main_category = serializers.CharField()
    f_name = serializers.CharField()
    price = serializers.CharField()
    rentability = serializers.CharField()
    desc_ukr = serializers.CharField()
    desc_ru = serializers.CharField()
    gpu_fps = serializers.CharField()
    gpu_m_s = serializers.CharField()
    gpu_b = serializers.CharField()
    gpu_cpu_spd = serializers.CharField()
    gpu_mem_spd = serializers.CharField()
    gpu_triple_fan_rus = serializers.CharField()
    gpu_triple_fan_ua = serializers.CharField()
    #depend_to = serializers.CharField()
    #depend_to_type = serializers.CharField()
    #more = serializers.CharField()
    label = serializers.CharField()
    gpu_warr_ua = serializers.CharField(max_length=300)
    gpu_warr_ru = serializers.CharField(max_length=300)


class FanSerializer(serializers.Serializer):
    name = serializers.CharField()
    part_number = serializers.CharField()
    vendor = serializers.CharField()
    price = serializers.CharField()
    rentability = serializers.CharField()
    desc_ukr = serializers.CharField()
    desc_ru = serializers.CharField()
    case_fan_spd_ua = serializers.CharField()
    case_fan_spd_rus = serializers.CharField()
    case_fan_noise_level = serializers.CharField()
    case_fan_size = serializers.CharField()
    #more = serializers.CharField()
    label = serializers.CharField()
    case_fan_warr_ua = serializers.CharField(max_length=300)
    case_fan_warr_ru = serializers.CharField(max_length=300)


class CaseSerializer(serializers.Serializer):
    name = serializers.CharField()
    part_number = serializers.CharField()
    vendor = serializers.CharField()
    price = serializers.CharField()
    rentability = serializers.CharField()
    desc_ukr = serializers.CharField()
    desc_ru = serializers.CharField()
    case_s = serializers.CharField()
    color_parent = serializers.CharField()
    color = serializers.CharField()
    color_ukr = serializers.CharField()
    color_ru = serializers.CharField()
    case_wcs_plus_size_ru = serializers.CharField()
    case_wcs_plus_size_ua = serializers.CharField()
    case_gpu_triple_fan_ua = serializers.CharField()
    case_gpu_triple_fan_ru = serializers.CharField()
    case_count_fan = serializers.CharField()
    #depend_to = serializers.CharField()
    #depend_to_type = serializers.CharField()
    case_height = serializers.CharField()
    #more = serializers.CharField()
    label = serializers.CharField()
    case_warr_ua = serializers.CharField(max_length=300)
    case_warr_ru = serializers.CharField(max_length=300)


class SsdSerializer(serializers.Serializer):
    name = serializers.CharField()
    part_number = serializers.CharField()
    vendor = serializers.CharField()
    f_name = serializers.CharField()
    price = serializers.CharField()
    rentability = serializers.CharField()
    desc_ukr = serializers.CharField()
    desc_ru = serializers.CharField()
    ssd_s = serializers.CharField()
    ssd_spd = serializers.CharField()
    ssd_r_spd = serializers.CharField()
    ssd_type_cells = serializers.CharField()
    #more = serializers.CharField()
    label = serializers.CharField()
    ssd_warr_ua = serializers.CharField(max_length=300)
    ssd_warr_ru = serializers.CharField(max_length=300)


class CablesSerializer(serializers.Serializer):
    name = serializers.CharField()
    part_number = serializers.CharField()
    vendor = serializers.CharField()
    r_price = serializers.CharField()
    rentability = serializers.CharField()
    desc_ukr = serializers.CharField()
    desc_ru = serializers.CharField()
    cab_mat_ukr = serializers.CharField()
    cab_mat_ru = serializers.CharField()
    cab_col_ukr = serializers.CharField()
    cab_col_ru = serializers.CharField()
    cab_set = serializers.CharField()
    #more = serializers.CharField()
    label = serializers.CharField()
    cab_warr_ua = serializers.CharField(max_length=300)
    cab_warr_ru = serializers.CharField(max_length=300)

class WiFiSerializer(serializers.Serializer):
    name = serializers.CharField()
    part_number = serializers.CharField()
    vendor = serializers.CharField()
    r_price = serializers.CharField()
    price = serializers.CharField()
    rentability = serializers.CharField()
    desc_ukr = serializers.CharField()
    desc_ru = serializers.CharField()
    net_type_ukr = serializers.CharField()
    net_type_rus = serializers.CharField()
    net_max_spd = serializers.CharField()
    net_stand = serializers.CharField()
    net_int = serializers.CharField()
    #more = serializers.CharField()
    label = serializers.CharField()
    net_warr_ua = serializers.CharField(max_length=300)
    net_warr_ru = serializers.CharField(max_length=300)

class SoftSerializer(serializers.Serializer):
    name = serializers.CharField()
    part_number = serializers.CharField()
    vendor = serializers.CharField()
    r_price = serializers.CharField()
    price = serializers.CharField()
    rentability = serializers.CharField()
    desc_ukr = serializers.CharField()
    desc_ru = serializers.CharField()
    soft_type_ukr = serializers.CharField()
    soft_type_ru = serializers.CharField()
    soft_lang_ukr = serializers.CharField()
    soft_lang_ru = serializers.CharField()
    soft_set = serializers.CharField()
    #more = serializers.CharField()
    label = serializers.CharField()
    soft_warr_ua = serializers.CharField(max_length=300)
    soft_warr_ru = serializers.CharField(max_length=300)
