# Generated by Django 3.1.1 on 2020-09-04 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Article_field')),
            ],
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(db_index=True, max_length=100, verbose_name='Item_name')),
                ('item_price', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Item_price')),
                ('item_article', models.CharField(db_index=True, max_length=100, verbose_name='Item_article')),
            ],
        ),
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_provider', models.CharField(choices=[('dc', 'dc-link'), ('itlink', 'it-link'), ('asbis', 'asbis'), ('elko', 'elko'), ('mti', 'mti'), ('brain', 'brain'), ('edg', 'edg'), ('erc', 'erc'), ('-', '-')], db_index=True, default='-', max_length=50, verbose_name='Name_provider')),
                ('more', models.TextField(blank=True, null=True, verbose_name='More_about_provider')),
            ],
            options={
                'verbose_name': 'Providers+',
                'verbose_name_plural': 'Provider',
            },
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sites', models.CharField(choices=[('itblok', 'it-blok'), ('versum', 'versum'), ('fury', 'digitalfury'), ('ua', 'uastore'), ('art', 'artline')], db_index=True, default='itblok', max_length=50, verbose_name='Name_sites')),
                ('more', models.TextField(blank=True, null=True, verbose_name='More_about_site')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
            },
        ),
        migrations.CreateModel(
            name='Parts_short',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_parts', models.CharField(db_index=True, max_length=300, verbose_name='Name_parts')),
                ('partnumber_list', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Partnumber_list')),
                ('x_code', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='X_code')),
                ('Advanced_parts', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Advanced_parts')),
                ('articles', models.ManyToManyField(to='cat.Articles')),
            ],
            options={
                'verbose_name': 'Parts_short',
                'verbose_name_plural': 'Parts_short+',
                'ordering': ['-name_parts'],
            },
        ),
        migrations.CreateModel(
            name='Parts_full',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_parts', models.CharField(db_index=True, max_length=300, verbose_name='Name_parts')),
                ('partnumber_parts', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Partnumber_parts')),
                ('provider', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Provider')),
                ('availability_parts', models.CharField(db_index=True, max_length=50, verbose_name='Availability_parts')),
                ('price_parts', models.CharField(db_index=True, max_length=50, verbose_name='price_parts')),
                ('url_parts', models.CharField(db_index=True, max_length=200, verbose_name='Url_parts')),
                ('item_parts', models.CharField(db_index=True, max_length=50, verbose_name='Item_parts')),
                ('providers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cat.providers')),
            ],
            options={
                'verbose_name': 'Parts_full',
                'verbose_name_plural': 'Parts_full+',
                'ordering': ['-name_parts'],
            },
        ),
        migrations.CreateModel(
            name='Computers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_computers', models.CharField(db_index=True, max_length=300, verbose_name='Name_computers')),
                ('url_computers', models.CharField(db_index=True, max_length=300, verbose_name='Url_computers')),
                ('price_computers', models.CharField(db_index=True, max_length=300, verbose_name='Price_computers')),
                ('proc_computers', models.CharField(db_index=True, max_length=300, verbose_name='Proc_computers')),
                ('mb_computers', models.CharField(db_index=True, max_length=300, verbose_name='Mb_computers')),
                ('mem_computers', models.CharField(db_index=True, max_length=300, verbose_name='Mem_computers')),
                ('video_computers', models.CharField(db_index=True, max_length=300, verbose_name='Video_computers')),
                ('hdd_computers', models.CharField(db_index=True, max_length=300, verbose_name='Hdd_computers')),
                ('ps_computers', models.CharField(db_index=True, max_length=300, verbose_name='Ps_computers')),
                ('case_computers', models.CharField(db_index=True, max_length=300, verbose_name='Case_computers')),
                ('cool_computers', models.CharField(db_index=True, max_length=300, verbose_name='Cool_computers')),
                ('class_computers', models.CharField(db_index=True, max_length=300, verbose_name='Class_computers')),
                ('warranty_computers', models.CharField(db_index=True, max_length=300, verbose_name='Warranty_computers')),
                ('parts_short', models.ManyToManyField(to='cat.Parts_short')),
                ('sites', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_query_name='entry', to='cat.sites', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Computer',
                'verbose_name_plural': 'Computers',
                'ordering': ['-name_computers'],
            },
        ),
        migrations.AddField(
            model_name='articles',
            name='pack',
            field=models.ManyToManyField(to='cat.Pack'),
        ),
    ]
