# Generated by Django 3.1.1 on 2020-09-04 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='pack',
        ),
        migrations.RemoveField(
            model_name='parts_short',
            name='articles',
        ),
        migrations.AddField(
            model_name='articles',
            name='item_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Item_name'),
        ),
        migrations.AddField(
            model_name='articles',
            name='item_price',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Item_price'),
        ),
        migrations.AddField(
            model_name='articles',
            name='parts_short',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cat.parts_short'),
        ),
        migrations.AddField(
            model_name='articles',
            name='providers',
            field=models.ManyToManyField(to='cat.Providers'),
        ),
        migrations.AlterField(
            model_name='parts_short',
            name='x_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='X_code'),
        ),
        migrations.DeleteModel(
            name='Pack',
        ),
    ]
