# Generated by Django 3.1.1 on 2020-09-07 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0002_auto_20200904_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parts_full',
            old_name='price_parts',
            new_name='providerprice_parts',
        ),
        migrations.RemoveField(
            model_name='parts_full',
            name='item_parts',
        ),
        migrations.RemoveField(
            model_name='parts_full',
            name='partnumber_parts',
        ),
        migrations.RemoveField(
            model_name='parts_full',
            name='provider',
        ),
    ]
