# Generated by Django 3.1.1 on 2020-09-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0003_auto_20200907_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computers',
            name='parts_short',
        ),
        migrations.AddField(
            model_name='parts_short',
            name='computers',
            field=models.ManyToManyField(to='cat.Computers'),
        ),
    ]
