# Generated by Django 3.1.1 on 2020-09-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0005_auto_20200908_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts_full',
            name='partnumber_parts',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Partnumber_parts'),
        ),
    ]
