# Generated by Django 3.1.1 on 2020-09-21 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0006_auto_20200915_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computers',
            name='sites',
        ),
        migrations.CreateModel(
            name='Pc_assembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_assembly', models.CharField(db_index=True, max_length=300, verbose_name='Name_assembly')),
                ('sites', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_query_name='entry', to='cat.sites', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Assembly',
                'verbose_name_plural': 'Assemblies',
            },
        ),
        migrations.AddField(
            model_name='computers',
            name='pc_assembly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cat.pc_assembly', verbose_name='Pc_assembly'),
        ),
    ]
