# Generated by Django 3.1.1 on 2020-09-22 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0008_auto_20200922_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='parts_short',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cat.computers'),
        ),
    ]
