# Generated by Django 3.1.1 on 2020-09-22 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0009_auto_20200922_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='parts_short',
            new_name='computers',
        ),
    ]
