# Generated by Django 3.1.1 on 2020-09-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0010_auto_20200922_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc_assembly',
            name='kind_assembly',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Kind_assembly'),
        ),
    ]
