# Generated by Django 3.1.1 on 2020-09-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0011_pc_assembly_kind_assembly'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts_short',
            name='computers',
            field=models.ManyToManyField(to='cat.Computers'),
        ),
    ]
