# Generated by Django 3.1.1 on 2020-10-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0012_parts_short_computers'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts_short',
            name='date_chg',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date_chg'),
        ),
        migrations.AddField(
            model_name='parts_short',
            name='min_price',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='min_price'),
        ),
    ]
