# Generated by Django 3.1.1 on 2020-11-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0014_parts_short_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='computers',
            name='mem_num_computers',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='Mem_computers'),
        ),
        migrations.AddField(
            model_name='computers',
            name='vent_computers',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='Cool_computers'),
        ),
        migrations.AddField(
            model_name='computers',
            name='video_num_computers',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='Video_computers'),
        ),
    ]
