# Generated by Django 3.1.1 on 2020-11-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0015_auto_20201117_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='computers',
            name='vent_num_computers',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='Cool_computers'),
        ),
    ]
