# Generated by Django 3.1.1 on 2020-12-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0016_computers_vent_num_computers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts_full',
            name='partnumber_parts',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='Partnumber_parts'),
        ),
        migrations.AlterField(
            model_name='parts_short',
            name='partnumber_list',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='Partnumber_list'),
        ),
    ]
