# Generated by Django 3.1.1 on 2020-12-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0017_auto_20201201_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts_full',
            name='remainder',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='remainder'),
        ),
    ]
