# Generated by Django 3.1.1 on 2021-01-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0020_auto_20201225_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts_full',
            name='date_chg',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date_chg'),
        ),
    ]
