# Generated by Django 3.1.1 on 2021-01-05 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0021_parts_full_date_chg'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompPrice',
            fields=[
                ('name_computers', models.CharField(db_index=True, max_length=300, verbose_name='Name_computers')),
                ('vent_computers', models.CharField(db_index=True, max_length=300, null=True, verbose_name='Url_computers')),
                ('price_computers', models.CharField(db_index=True, max_length=300, null=True, verbose_name='Price_computers')),
                ('proc_computers', models.CharField(db_index=True, max_length=300, null=True, verbose_name='Proc_computers')),
                ('mb_computers', models.CharField(db_index=True, max_length=300, null=True, verbose_name='Mb_computers')),
                ('mem_computers', models.CharField(db_index=True, max_length=300, null=True, verbose_name='Mem_computers')),
                ('video_computers', models.CharField(db_index=True, max_length=300, null=True, verbose_name='Video_computers')),
                ('hdd_computers', models.CharField(db_index=True, max_length=300, null=True, verbose_name='Hdd_computers')),
                ('hdd2_computers', models.CharField(db_index=True, max_length=300, null=True, verbose_name='Hdd_computers')),
                ('ps_computers', models.CharField(db_index=True, max_length=300, null=True, verbose_name='Ps_computers')),
                ('case_computers', models.CharField(db_index=True, max_length=300, null=True, verbose_name='Case_computers')),
                ('cool_computers', models.CharField(db_index=True, max_length=300, null=True, verbose_name='Cool_computers')),
                ('computers', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cat.computers')),
            ],
            options={
                'verbose_name': 'CompPrice',
                'verbose_name_plural': 'CompPrices',
                'ordering': ['-name_computers'],
            },
        ),
    ]
