# Generated by Django 3.1.1 on 2021-01-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0024_auto_20210114_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='computers',
            name='date_computers',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
