# Generated by Django 3.1.1 on 2021-01-28 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0026_auto_20210128_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parts_short',
            old_name='computers',
            new_name='parts_full',
        ),
    ]
