# Generated by Django 3.1.1 on 2021-01-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0027_auto_20210128_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts_short',
            name='kind2',
            field=models.BooleanField(default=False),
        ),
    ]
