# Generated by Django 3.1.1 on 2021-02-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0028_parts_short_kind2'),
    ]

    operations = [
        migrations.AddField(
            model_name='computers',
            name='km_computers',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='km_computers'),
        ),
        migrations.AddField(
            model_name='computers',
            name='mon_computers',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='mon_computers'),
        ),
        migrations.AddField(
            model_name='computers',
            name='wifi_computers',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='wifi_computers'),
        ),
    ]
