# Generated by Django 3.1.1 on 2021-03-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0030_auto_20210222_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='USD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd', models.FloatField(db_index=True, verbose_name='usd')),
                ('date_ch', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
