# Generated by Django 3.1.1 on 2021-04-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0031_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts_full',
            name='is_hot',
            field=models.BooleanField(default=True),
        ),
    ]
