# Generated by Django 3.1.1 on 2021-05-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0033_parts_full_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='computers',
            name='prom_computers',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='prom_computers'),
        ),
    ]
