# Generated by Django 3.1.1 on 2021-05-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0034_computers_prom_computers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computers',
            name='prom_computers',
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prom', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='promotions')),
                ('computers', models.ManyToManyField(to='cat.Computers')),
            ],
        ),
    ]
