# Generated by Django 3.1.1 on 2021-05-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0035_auto_20210505_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=300, verbose_name='Name_ssd')),
                ('part_number', models.CharField(db_index=True, max_length=300, verbose_name='Part_number')),
                ('vendor', models.CharField(db_index=True, max_length=300, verbose_name='Vendor')),
                ('r_price', models.CharField(db_index=True, max_length=300, verbose_name='r_price')),
                ('desc_ukr', models.TextField(db_index=True, verbose_name='Desc_ukr')),
                ('desc_ru', models.TextField(db_index=True, verbose_name='Desc_ru')),
                ('cab_mat_ukr', models.CharField(db_index=True, max_length=300, verbose_name='cab_mat_ukr')),
                ('cab_mat_ru', models.CharField(db_index=True, max_length=300, verbose_name='cab_mat_ru')),
                ('cab_col_ukr', models.CharField(db_index=True, max_length=300, verbose_name='cab_col_ukr')),
                ('cab_col_ru', models.CharField(db_index=True, max_length=300, verbose_name='cab_col_ru')),
                ('cab_set', models.CharField(db_index=True, max_length=300, verbose_name='cab_set')),
                ('more', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='More')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Soft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=300, verbose_name='Name_ssd')),
                ('part_number', models.CharField(db_index=True, max_length=300, verbose_name='Part_number')),
                ('vendor', models.CharField(db_index=True, max_length=300, verbose_name='Vendor')),
                ('r_price', models.CharField(db_index=True, max_length=300, verbose_name='r_price')),
                ('price', models.CharField(db_index=True, max_length=300, verbose_name='Price')),
                ('desc_ukr', models.TextField(db_index=True, verbose_name='Desc_ukr')),
                ('desc_ru', models.TextField(db_index=True, verbose_name='Desc_ru')),
                ('soft_type_ukr', models.CharField(db_index=True, max_length=300, verbose_name='soft_type_ukr')),
                ('soft_type_ru', models.CharField(db_index=True, max_length=300, verbose_name='soft_type_ru')),
                ('soft_lang_ukr', models.CharField(db_index=True, max_length=300, verbose_name='soft_lang_ukr')),
                ('soft_lang_ru', models.CharField(db_index=True, max_length=300, verbose_name='soft_lang_ru')),
                ('soft_set', models.CharField(db_index=True, max_length=300, verbose_name='soft_set')),
                ('more', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='More')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WiFi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=300, verbose_name='Name_ssd')),
                ('part_number', models.CharField(db_index=True, max_length=300, verbose_name='Part_number')),
                ('vendor', models.CharField(db_index=True, max_length=300, verbose_name='Vendor')),
                ('r_price', models.CharField(db_index=True, max_length=300, verbose_name='r_price')),
                ('price', models.CharField(db_index=True, max_length=300, verbose_name='Price')),
                ('desc_ukr', models.TextField(db_index=True, verbose_name='Desc_ukr')),
                ('desc_ru', models.TextField(db_index=True, verbose_name='Desc_ru')),
                ('net_type_ukr', models.CharField(db_index=True, max_length=300, verbose_name='net_type_ukr')),
                ('net_type_rus', models.CharField(db_index=True, max_length=300, verbose_name='net_type_rus')),
                ('net_max_spd', models.CharField(db_index=True, max_length=300, verbose_name='net_max_spd')),
                ('net_stand', models.CharField(db_index=True, max_length=300, verbose_name='net_stand')),
                ('net_int', models.CharField(db_index=True, max_length=300, verbose_name='net_int')),
                ('more', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='More')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
