# Generated by Django 3.1.1 on 2021-05-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0037_auto_20210513_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='compprice',
            name='cables_computers',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='cables_computers'),
        ),
        migrations.AddField(
            model_name='compprice',
            name='soft_computers',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='soft_computers'),
        ),
    ]
