# Generated by Django 3.1.1 on 2021-05-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0038_auto_20210513_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='english_prom',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='english_prom'),
        ),
    ]
