# Generated by Django 3.1.1 on 2021-05-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0039_promotion_english_prom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='computers',
        ),
        migrations.AddField(
            model_name='articles',
            name='parts_full',
            field=models.ManyToManyField(to='cat.Parts_full'),
        ),
    ]
