# Generated by Django 3.2.5 on 2021-07-11 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0040_auto_20210525_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parts_full',
            options={'ordering': ['providers__name_provider'], 'verbose_name': 'Parts_full', 'verbose_name_plural': 'Parts_full+'},
        ),
    ]
