# Generated by Django 3.1.1 on 2021-11-11 15:45

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0042_auto_20211102_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': [django.db.models.expressions.F('prom_len')]},
        ),
    ]
