# Generated by Django 3.1.1 on 2021-11-11 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0043_auto_20211111_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={},
        ),
    ]
