# Generated by Django 3.1.1 on 2021-11-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0046_auto_20211111_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='english_prom',
            field=models.CharField(db_index=True, default='empty', max_length=300, verbose_name='english_prom'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='prom',
            field=models.CharField(db_index=True, default='пусто', max_length=300, verbose_name='promotions'),
        ),
    ]
