# Generated by Django 3.1.1 on 2021-11-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0048_auto_20211112_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='item_price',
            field=models.CharField(blank=True, choices=[('cool', 'cool'), ('imb', 'imb'), ('amb', 'amb'), ('case', 'case'), ('ssd', 'ssd'), ('hdd', 'hdd'), ('aproc', 'aproc'), ('iproc', 'iproc'), ('video', 'video'), ('ps', 'ps'), ('mem', 'mem'), ('vent', 'vent'), ('mon', 'mon'), ('wifi', 'wifi'), ('km', 'km'), ('soft', 'soft'), ('cables', 'cables')], db_index=True, max_length=50, null=True, verbose_name='Item_price'),
        ),
    ]
