# Generated by Django 3.1.1 on 2021-11-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0049_auto_20211112_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='One_C',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='somebody', max_length=100, verbose_name='Name')),
                ('text_test', models.TextField(blank=True, db_index=True, max_length=5000, null=True, verbose_name='text_test')),
                ('date_ch', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date_ch'],
            },
        ),
    ]
