# Generated by Django 3.1.1 on 2021-11-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0050_one_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='one_c',
            name='json_data',
            field=models.JSONField(blank=True, null=True, verbose_name='json_data'),
        ),
    ]
