# Generated by Django 3.1.1 on 2021-12-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0051_one_c_json_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='english_prom',
            field=models.CharField(blank=True, db_index=True, default='empty', max_length=300, null=True, verbose_name='english_prom'),
        ),
    ]
