# Generated by Django 3.1.1 on 2022-01-27 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0054_auto_20220127_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewComps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_name', models.CharField(db_index=True, max_length=300, verbose_name='New_name')),
            ],
        ),
        migrations.AddField(
            model_name='parts_short',
            name='mb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mb', to='cat.newcomps'),
        ),
        migrations.AddField(
            model_name='parts_short',
            name='proc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proc', to='cat.newcomps'),
        ),
    ]
