# Generated by Django 3.1.1 on 2022-01-28 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0055_auto_20220127_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts_short',
            name='mb',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'amb'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mb', to='cat.newcomps'),
        ),
        migrations.AlterField(
            model_name='parts_short',
            name='proc',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'aproc'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proc', to='cat.newcomps'),
        ),
    ]
