# Generated by Django 3.1.1 on 2022-01-28 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0056_auto_20220128_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parts_short',
            name='mb',
        ),
        migrations.RemoveField(
            model_name='parts_short',
            name='proc',
        ),
    ]
