# Generated by Django 3.1.1 on 2022-01-28 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0057_auto_20220128_1152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewComps',
        ),
    ]
