# Generated by Django 3.1.1 on 2022-02-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0058_delete_newcomps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts_full',
            name='availability_parts',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no'), ('q', 'q'), ('hand', 'hand')], db_index=True, max_length=50, null=True, verbose_name='Availability_parts'),
        ),
    ]
