# Generated by Django 3.1.1 on 2022-02-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0061_auto_20220210_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='item_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='item_price',
            field=models.CharField(blank=True, choices=[('cool', 'cool'), ('imb', 'imb'), ('amb', 'amb'), ('case', 'case'), ('ssd', 'ssd'), ('hdd', 'hdd'), ('aproc', 'aproc'), ('iproc', 'iproc'), ('video', 'video'), ('ps', 'ps'), ('mem', 'mem'), ('vent', 'vent'), ('mon', 'mon'), ('wifi', 'wifi'), ('km', 'km'), ('soft', 'soft'), ('cables', 'cables')], db_index=True, max_length=50, null=True, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='computers',
            name='cables_computers',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='Кабеля'),
        ),
        migrations.AlterField(
            model_name='computers',
            name='case_computers',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='computers',
            name='cool_computers',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Кулер'),
        ),
        migrations.AlterField(
            model_name='computers',
            name='hdd_computers',
            field=models.CharField(db_index=True, max_length=300, verbose_name='HDD_SSD'),
        ),
        migrations.AlterField(
            model_name='computers',
            name='km_computers',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='Клав. мышь'),
        ),
        migrations.AlterField(
            model_name='computers',
            name='mb_computers',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Материнская плата'),
        ),
        migrations.AlterField(
            model_name='computers',
            name='mem_computers',
            field=models.CharField(db_index=True, max_length=300, verbose_name='ОЗУ'),
        ),
        migrations.AlterField(
            model_name='computers',
            name='mem_num_computers',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='ОЗУ кол'),
        ),
        migrations.AlterField(
            model_name='computers',
            name='mon_computers',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='Монитор'),
        ),
        migrations.AlterField(
            model_name='computers',
            name='name_computers',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Имя компьютера'),
        ),
        migrations.AlterField(
            model_name='computers',
            name='price_computers',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='computers',
            name='proc_computers',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Процессор'),
        ),
        migrations.AlterField(
            model_name='computers',
            name='ps_computers',
            field=models.CharField(db_index=True, max_length=300, verbose_name='БП'),
        ),
        migrations.AlterField(
            model_name='computers',
            name='soft_computers',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='Софт'),
        ),
        migrations.AlterField(
            model_name='computers',
            name='url_computers',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='computers',
            name='vent_computers',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='Вентилятор'),
        ),
        migrations.AlterField(
            model_name='computers',
            name='vent_num_computers',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='Вентиляторы кол'),
        ),
        migrations.AlterField(
            model_name='computers',
            name='video_computers',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Видеокарта'),
        ),
        migrations.AlterField(
            model_name='computers',
            name='video_num_computers',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='Видеокарты кол'),
        ),
        migrations.AlterField(
            model_name='computers',
            name='wifi_computers',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='WIFI'),
        ),
        migrations.AlterField(
            model_name='parts_full',
            name='availability_parts',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no'), ('q', 'q'), ('hand', 'hand')], db_index=True, max_length=50, null=True, verbose_name='Наличие или авто-руч'),
        ),
        migrations.AlterField(
            model_name='parts_full',
            name='date_chg',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата посл. изменения'),
        ),
        migrations.AlterField(
            model_name='parts_full',
            name='kind',
            field=models.CharField(blank=True, choices=[('cool', 'cool'), ('imb', 'imb'), ('amb', 'amb'), ('case', 'case'), ('ssd', 'ssd'), ('hdd', 'hdd'), ('aproc', 'aproc'), ('iproc', 'iproc'), ('video', 'video'), ('ps', 'ps'), ('mem', 'mem'), ('vent', 'vent'), ('mon', 'mon'), ('wifi', 'wifi'), ('km', 'km'), ('soft', 'soft'), ('cables', 'cables')], db_index=True, max_length=50, null=True, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='parts_full',
            name='name_parts',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='parts_full',
            name='partnumber_parts',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='parts_full',
            name='providerprice_parts',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='parts_short',
            name='date_chg',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата посл. изменения'),
        ),
        migrations.AlterField(
            model_name='parts_short',
            name='kind',
            field=models.CharField(blank=True, choices=[('cool', 'cool'), ('imb', 'imb'), ('amb', 'amb'), ('case', 'case'), ('ssd', 'ssd'), ('hdd', 'hdd'), ('aproc', 'aproc'), ('iproc', 'iproc'), ('video', 'video'), ('ps', 'ps'), ('mem', 'mem'), ('vent', 'vent'), ('mon', 'mon'), ('wifi', 'wifi'), ('km', 'km'), ('soft', 'soft'), ('cables', 'cables')], db_index=True, max_length=50, null=True, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='parts_short',
            name='name_parts',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='parts_short',
            name='partnumber_list',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='Служ код'),
        ),
        migrations.AlterField(
            model_name='parts_short',
            name='x_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='pc_assembly',
            name='desc_ru',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True, verbose_name='Описание_укр'),
        ),
        migrations.AlterField(
            model_name='pc_assembly',
            name='desc_ukr',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True, verbose_name='Описание_рус'),
        ),
        migrations.AlterField(
            model_name='pc_assembly',
            name='kind_assembly',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='pc_assembly',
            name='name_assembly',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='english_prom',
            field=models.CharField(blank=True, db_index=True, default='empty', max_length=300, null=True, verbose_name='Ярлык(англ)'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='prom',
            field=models.CharField(db_index=True, default='пусто', max_length=300, verbose_name='Ярлык'),
        ),
    ]
