# Generated by Django 3.1.1 on 2022-03-09 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0062_auto_20220217_0652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Артикул', 'verbose_name_plural': 'Артикулы'},
        ),
        migrations.AlterModelOptions(
            name='computers',
            options={'ordering': ['-name_computers'], 'verbose_name': 'Компьютер', 'verbose_name_plural': 'Компьютеры'},
        ),
        migrations.AlterModelOptions(
            name='parts_full',
            options={'ordering': ['providers__name_provider'], 'verbose_name': 'Прайс', 'verbose_name_plural': 'Прайс'},
        ),
        migrations.AlterModelOptions(
            name='parts_short',
            options={'ordering': ['-name_parts'], 'verbose_name': 'Компьютерная деталь', 'verbose_name_plural': 'Компьютерные детали'},
        ),
        migrations.AlterModelOptions(
            name='pc_assembly',
            options={'verbose_name': 'Компьютерная сборка', 'verbose_name_plural': 'Компьютерные сборки'},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['prom__length'], 'verbose_name': 'Компьютерный ярлык', 'verbose_name_plural': 'Компьютерные ярлыки'},
        ),
        migrations.AlterField(
            model_name='computers',
            name='pc_assembly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cat.pc_assembly', verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='parts_full',
            name='providers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cat.providers', verbose_name='Поставщики'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='computers',
            field=models.ManyToManyField(limit_choices_to={'pc_assembly__sites__name_sites': 'versum'}, to='cat.Computers', verbose_name='Компьютеры'),
        ),
    ]
