# Generated by Django 3.1.1 on 2022-04-13 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0063_auto_20220309_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer_code',
            fields=[
                ('comp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='code', serialize=False, to='cat.computers')),
                ('cpu_code', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='код процессора')),
                ('video_code', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='код видео')),
                ('mem_code', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='код памяти')),
                ('video_html_code', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='код видео нтмл')),
                ('code_is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
