# Generated by Django 3.1.1 on 2022-05-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0065_auto_20220517_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts_short',
            name='kind',
            field=models.CharField(blank=True, choices=[('cool', 'cool'), ('imb', 'imb'), ('amb', 'amb'), ('case', 'case'), ('ssd', 'ssd'), ('hdd', 'hdd'), ('aproc', 'aproc'), ('iproc', 'iproc'), ('video', 'video'), ('ps', 'ps'), ('mem', 'mem'), ('vent', 'vent'), ('mon', 'mon'), ('wifi', 'wifi'), ('km', 'km'), ('soft', 'soft'), ('cables', 'cables')], db_index=True, max_length=50, null=True, verbose_name='Вид'),
        ),
    ]
