# Generated by Django 3.1.1 on 2022-05-25 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('descriptions', '0002_auto_20220309_1626'),
        ('cat', '0066_auto_20220517_0756'),
    ]

    operations = [
         migrations.AlterField(
            model_name='parts_full',
            name='name_parts_main',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='1 поставщик'),
        ),
    ]
