# Generated by Django 3.1.1 on 2022-05-25 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('descriptions', '0002_auto_20220309_1626'),
        ('cat', '0067_auto_20220525_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts_short',
            name='cables_shorts',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='descriptions.cables'),
        ),
        migrations.AddField(
            model_name='parts_short',
            name='case_shorts',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='descriptions.case'),
        ),
        migrations.AddField(
            model_name='parts_short',
            name='computer_shorts',
            field=models.ManyToManyField(to='cat.Computers'),
        ),
        migrations.AddField(
            model_name='parts_short',
            name='cooler_shorts',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='descriptions.cooler'),
        ),
        migrations.AddField(
            model_name='parts_short',
            name='cpu_shorts',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='descriptions.cpu'),
        ),
        migrations.AddField(
            model_name='parts_short',
            name='fan_shorts',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='descriptions.fan'),
        ),
        migrations.AddField(
            model_name='parts_short',
            name='gpu_shorts',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='descriptions.gpu'),
        ),
        migrations.AddField(
            model_name='parts_short',
            name='hdd_shorts',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='descriptions.hdd'),
        ),
        migrations.AddField(
            model_name='parts_short',
            name='mb_shorts',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='descriptions.mb'),
        ),
        migrations.AddField(
            model_name='parts_short',
            name='psu_shorts',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='descriptions.psu'),
        ),
        migrations.AddField(
            model_name='parts_short',
            name='ram_shorts',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='descriptions.ram'),
        ),
        migrations.AddField(
            model_name='parts_short',
            name='soft_shorts',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='descriptions.soft'),
        ),
        migrations.AddField(
            model_name='parts_short',
            name='ssd_shorts',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='descriptions.ssd'),
        ),
        migrations.AddField(
            model_name='parts_short',
            name='wifi_shorts',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='descriptions.wifi'),
        ),
    ]
