# Generated by Django 3.1.1 on 2022-06-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0068_auto_20220525_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts_full',
            name='providerprice_parts',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='parts_short',
            name='min_price',
            field=models.FloatField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Цена,ручная'),
        ),
        migrations.AlterField(
            model_name='parts_short',
            name='x_code',
            field=models.FloatField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Цена'),
        ),
    ]
