# Generated by Django 3.1.1 on 2022-06-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0069_auto_20220610_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts_short',
            name='auto',
            field=models.BooleanField(default=False, verbose_name='ручная/поставщики'),
        ),
    ]
