# Generated by Django 3.1.1 on 2022-07-19 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('descriptions', '0005_auto_20220719_1547'),
        ('cat', '0070_parts_short_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts_short',
            name='Advanced_parts',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Колличество'),
        ),
        migrations.AlterField(
            model_name='parts_short',
            name='cables_shorts',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='descriptions.cables', verbose_name='Кабеля'),
        ),
        migrations.AlterField(
            model_name='parts_short',
            name='case_shorts',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='descriptions.case', verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='parts_short',
            name='computer_shorts',
            field=models.ManyToManyField(to='cat.Computers', verbose_name='Комп'),
        ),
        migrations.AlterField(
            model_name='parts_short',
            name='cooler_shorts',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='descriptions.cooler', verbose_name='Кулер'),
        ),
        migrations.AlterField(
            model_name='parts_short',
            name='cpu_shorts',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='descriptions.cpu', verbose_name='Проц'),
        ),
        migrations.AlterField(
            model_name='parts_short',
            name='fan_shorts',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='descriptions.fan', verbose_name='Вентлтр'),
        ),
        migrations.AlterField(
            model_name='parts_short',
            name='gpu_shorts',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='descriptions.gpu', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='parts_short',
            name='hdd_shorts',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='descriptions.hdd', verbose_name='Ждиск'),
        ),
        migrations.AlterField(
            model_name='parts_short',
            name='mb_shorts',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='descriptions.mb', verbose_name='Мать'),
        ),
        migrations.AlterField(
            model_name='parts_short',
            name='parts_full',
            field=models.ManyToManyField(to='cat.Parts_full', verbose_name='Прайс'),
        ),
        migrations.AlterField(
            model_name='parts_short',
            name='psu_shorts',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='descriptions.psu', verbose_name='БП'),
        ),
        migrations.AlterField(
            model_name='parts_short',
            name='ram_shorts',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='descriptions.ram', verbose_name='Память'),
        ),
        migrations.AlterField(
            model_name='parts_short',
            name='soft_shorts',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='descriptions.soft', verbose_name='Софт'),
        ),
        migrations.AlterField(
            model_name='parts_short',
            name='ssd_shorts',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='descriptions.ssd', verbose_name='ССД'),
        ),
        migrations.AlterField(
            model_name='parts_short',
            name='wifi_shorts',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='descriptions.wifi', verbose_name='ВайФай'),
        ),
        migrations.AlterField(
            model_name='pc_assembly',
            name='sites',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_query_name='entry', to='cat.sites', verbose_name='Сайт'),
        ),
    ]
