# Generated by Django 3.1.1 on 2022-08-24 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0071_auto_20220719_1547'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parts_short',
            unique_together={('name_parts', 'kind', 'kind2')},
        ),
    ]
