# Generated by Django 3.1.1 on 2022-08-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0072_auto_20220824_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computers',
            name='class_computers',
            field=models.FloatField(db_index=True, default=1.17, max_length=30, verbose_name='Наценка'),
        ),
    ]
