# Generated by Django 3.1.1 on 2022-08-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0073_auto_20220828_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usd',
            options={'verbose_name': 'USD', 'verbose_name_plural': 'USD'},
        ),
        migrations.AlterField(
            model_name='computers',
            name='cables_computers',
            field=models.CharField(db_index=True, default='пусто', max_length=300, verbose_name='Кабеля'),
        ),
        migrations.AlterField(
            model_name='computers',
            name='elite_conf',
            field=models.CharField(db_index=True, default='пусто', max_length=300, verbose_name='elite_conf'),
        ),
        migrations.AlterField(
            model_name='computers',
            name='km_computers',
            field=models.CharField(db_index=True, default='пусто', max_length=300, verbose_name='Клав. мышь'),
        ),
        migrations.AlterField(
            model_name='computers',
            name='mem_num_computers',
            field=models.CharField(db_index=True, default='1', max_length=300, verbose_name='ОЗУ кол'),
        ),
        migrations.AlterField(
            model_name='computers',
            name='mon_computers',
            field=models.CharField(db_index=True, default='пусто', max_length=300, verbose_name='Монитор'),
        ),
        migrations.AlterField(
            model_name='computers',
            name='perm_conf',
            field=models.CharField(db_index=True, default='пусто', max_length=300, verbose_name='perm_conf'),
        ),
        migrations.AlterField(
            model_name='computers',
            name='soft_computers',
            field=models.CharField(db_index=True, default='пусто', max_length=300, verbose_name='Софт'),
        ),
        migrations.AlterField(
            model_name='computers',
            name='vent_computers',
            field=models.CharField(db_index=True, default='пусто', max_length=300, verbose_name='Вентилятор'),
        ),
        migrations.AlterField(
            model_name='computers',
            name='vent_num_computers',
            field=models.CharField(db_index=True, default='1', max_length=300, verbose_name='Вентиляторы кол'),
        ),
        migrations.AlterField(
            model_name='computers',
            name='video_num_computers',
            field=models.CharField(db_index=True, default='1', max_length=300, verbose_name='Видеокарты кол'),
        ),
        migrations.AlterField(
            model_name='computers',
            name='wifi_computers',
            field=models.CharField(db_index=True, default='пусто', max_length=300, verbose_name='WIFI'),
        ),
        migrations.AlterField(
            model_name='computers',
            name='you_vid',
            field=models.CharField(db_index=True, default='пусто', max_length=300, verbose_name='you_vid'),
        ),
    ]
