# Generated by Django 3.1.1 on 2022-10-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0075_auto_20220923_0910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pc_assembly',
            options={'verbose_name': 'Серии сайта', 'verbose_name_plural': 'Серии сайта'},
        ),
        migrations.AlterModelOptions(
            name='results',
            options={'ordering': ['date_ch'], 'verbose_name': '_Результаты выгрузок', 'verbose_name_plural': '_Результаты выгрузок'},
        ),
        migrations.AlterField(
            model_name='results',
            name='date_ch',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='results',
            name='who',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='От кого'),
        ),
        migrations.AlterField(
            model_name='results',
            name='who_desc',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='Инфо'),
        ),
    ]
