# Generated by Django 4.1.6 on 2023-03-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0076_auto_20221003_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='computers',
            name='time_assembly_ru',
            field=models.CharField(choices=[('Готов к отправке', 'Готов к отправке'), ('Сборка 1-2 дня', 'Сборка 1-2 дня'), ('Сборка 3-5 дней', 'Сборка 3-5 дней')], db_index=True, default='Сборка 3-5 дней', max_length=50, verbose_name='Срок сборки(ру)'),
        ),
        migrations.AddField(
            model_name='computers',
            name='time_assembly_ukr',
            field=models.CharField(choices=[('Готовий до відправки', 'Готовий до відправки'), ('Збірка 1-2 днів', 'Збірка 1-2 днів'), ('Збірка 3-5 днів', 'Збірка 3-5 днів')], db_index=True, default='Збірка 3-5 днів', max_length=50, verbose_name='Срок сборки(укр)'),
        ),
        migrations.AddField(
            model_name='parts_short',
            name='config',
            field=models.BooleanField(default=True, verbose_name='конфигуратор/нет'),
        ),
        migrations.AlterField(
            model_name='computers',
            name='price_computers',
            field=models.FloatField(db_index=True, default=0, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='parts_short',
            name='min_price',
            field=models.FloatField(db_index=True, default=0, max_length=50, verbose_name='Цена,ручная'),
        ),
        migrations.AlterField(
            model_name='parts_short',
            name='x_code',
            field=models.FloatField(db_index=True, default=0, max_length=50, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='pc_assembly',
            name='desc_ru',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True, verbose_name='Описание_рус'),
        ),
        migrations.AlterField(
            model_name='pc_assembly',
            name='desc_ukr',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True, verbose_name='Описание_укр'),
        ),
    ]
