# Generated by Django 3.1.1 on 2022-03-09 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('descriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cables',
            options={'ordering': ['name'], 'verbose_name': 'Кабеля', 'verbose_name_plural': 'Кабеля'},
        ),
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['name'], 'verbose_name': 'Корпус', 'verbose_name_plural': 'Корпуса'},
        ),
        migrations.AlterModelOptions(
            name='cooler',
            options={'ordering': ['name'], 'verbose_name': 'Кулер', 'verbose_name_plural': 'Кулеры'},
        ),
        migrations.AlterModelOptions(
            name='cpu',
            options={'ordering': ['name'], 'verbose_name': 'Процессор', 'verbose_name_plural': 'Процессоры'},
        ),
        migrations.AlterModelOptions(
            name='fan',
            options={'ordering': ['name'], 'verbose_name': 'Вентилятор', 'verbose_name_plural': 'Вентиляторы'},
        ),
        migrations.AlterModelOptions(
            name='gpu',
            options={'ordering': ['name'], 'verbose_name': 'Видеокарта', 'verbose_name_plural': 'Видеокарты'},
        ),
        migrations.AlterModelOptions(
            name='hdd',
            options={'ordering': ['name'], 'verbose_name': 'Жесткий диск', 'verbose_name_plural': 'Жесткие диски'},
        ),
        migrations.AlterModelOptions(
            name='mb',
            options={'ordering': ['name'], 'verbose_name': 'Материнская плата', 'verbose_name_plural': 'Материнские платы'},
        ),
        migrations.AlterModelOptions(
            name='psu',
            options={'ordering': ['name'], 'verbose_name': 'БП', 'verbose_name_plural': 'БП'},
        ),
        migrations.AlterModelOptions(
            name='ram',
            options={'ordering': ['name'], 'verbose_name': 'Память', 'verbose_name_plural': 'Память'},
        ),
        migrations.AlterModelOptions(
            name='soft',
            options={'ordering': ['name'], 'verbose_name': 'ПО', 'verbose_name_plural': 'ПО'},
        ),
        migrations.AlterModelOptions(
            name='ssd',
            options={'ordering': ['name'], 'verbose_name': 'SSD', 'verbose_name_plural': 'SSD'},
        ),
        migrations.AlterModelOptions(
            name='wifi',
            options={'ordering': ['name'], 'verbose_name': 'WIFI', 'verbose_name_plural': 'WIFI'},
        ),
    ]
