# Generated by Django 3.1.1 on 2022-06-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descriptions', '0002_auto_20220309_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooler',
            name='price',
            field=models.FloatField(db_index=True, max_length=300, verbose_name='Price'),
        ),
    ]
