# Generated by Django 3.1.1 on 2022-06-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descriptions', '0003_auto_20220604_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cables',
            name='r_price',
            field=models.FloatField(db_index=True, max_length=300, verbose_name='r_price'),
        ),
        migrations.AlterField(
            model_name='case',
            name='price',
            field=models.FloatField(db_index=True, max_length=300, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='case_other',
            name='r_price',
            field=models.FloatField(blank=True, db_index=True, max_length=300, null=True, verbose_name='r_price'),
        ),
        migrations.AlterField(
            model_name='cooler_other',
            name='r_price',
            field=models.FloatField(blank=True, db_index=True, max_length=300, null=True, verbose_name='r_price'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='price',
            field=models.FloatField(db_index=True, max_length=300, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='cpu_other',
            name='r_price',
            field=models.FloatField(blank=True, db_index=True, max_length=300, null=True, verbose_name='r_price'),
        ),
        migrations.AlterField(
            model_name='fan',
            name='price',
            field=models.FloatField(db_index=True, max_length=300, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='fan_other',
            name='r_price',
            field=models.FloatField(blank=True, db_index=True, max_length=300, null=True, verbose_name='r_price'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='price',
            field=models.FloatField(db_index=True, max_length=300, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='gpu_other',
            name='r_price',
            field=models.FloatField(blank=True, db_index=True, max_length=300, null=True, verbose_name='r_price'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='price',
            field=models.FloatField(db_index=True, max_length=300, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='hdd_other',
            name='r_price',
            field=models.FloatField(blank=True, db_index=True, max_length=300, null=True, verbose_name='r_price'),
        ),
        migrations.AlterField(
            model_name='mb',
            name='price',
            field=models.FloatField(db_index=True, max_length=300, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='mb_other',
            name='r_price',
            field=models.FloatField(blank=True, db_index=True, max_length=300, null=True, verbose_name='r_price'),
        ),
        migrations.AlterField(
            model_name='psu',
            name='price',
            field=models.FloatField(db_index=True, max_length=300, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='psu_other',
            name='r_price',
            field=models.FloatField(blank=True, db_index=True, max_length=300, null=True, verbose_name='r_price'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='price',
            field=models.FloatField(db_index=True, max_length=300, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='ram_other',
            name='r_price',
            field=models.FloatField(blank=True, db_index=True, max_length=300, null=True, verbose_name='r_price'),
        ),
        migrations.AlterField(
            model_name='soft',
            name='r_price',
            field=models.FloatField(db_index=True, max_length=300, verbose_name='r_price'),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='price',
            field=models.FloatField(db_index=True, max_length=300, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='ssd_other',
            name='r_price',
            field=models.FloatField(blank=True, db_index=True, max_length=300, null=True, verbose_name='r_price'),
        ),
        migrations.AlterField(
            model_name='wifi',
            name='r_price',
            field=models.FloatField(db_index=True, max_length=300, verbose_name='r_price'),
        ),
    ]
