# Generated by Django 3.1.1 on 2022-07-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descriptions', '0004_auto_20220604_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_height',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='case_height'),
        ),
        migrations.AddField(
            model_name='cooler',
            name='cooler_height',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='cooler_height'),
        ),
    ]
