# Generated by Django 3.1.1 on 2022-07-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descriptions', '0005_auto_20220719_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='depend_to',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='Depend_to'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='depend_to_type',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='Depend_to_type'),
        ),
        migrations.AlterField(
            model_name='cables',
            name='name',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Name_cables'),
        ),
        migrations.AlterField(
            model_name='soft',
            name='name',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Name_soft'),
        ),
        migrations.AlterField(
            model_name='wifi',
            name='name',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Name_wifi'),
        ),
    ]
