# Generated by Django 3.1.1 on 2022-08-28 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('descriptions', '0006_auto_20220726_1422'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cables',
            unique_together={('part_number', 'is_active')},
        ),
        migrations.AlterUniqueTogether(
            name='case',
            unique_together={('part_number', 'is_active')},
        ),
        migrations.AlterUniqueTogether(
            name='cooler',
            unique_together={('part_number', 'is_active')},
        ),
        migrations.AlterUniqueTogether(
            name='cpu',
            unique_together={('part_number', 'is_active')},
        ),
        migrations.AlterUniqueTogether(
            name='fan',
            unique_together={('part_number', 'is_active')},
        ),
        migrations.AlterUniqueTogether(
            name='gpu',
            unique_together={('part_number', 'is_active')},
        ),
        migrations.AlterUniqueTogether(
            name='hdd',
            unique_together={('part_number', 'is_active')},
        ),
        migrations.AlterUniqueTogether(
            name='mb',
            unique_together={('part_number', 'is_active')},
        ),
        migrations.AlterUniqueTogether(
            name='psu',
            unique_together={('part_number', 'is_active')},
        ),
        migrations.AlterUniqueTogether(
            name='ram',
            unique_together={('part_number', 'is_active')},
        ),
        migrations.AlterUniqueTogether(
            name='soft',
            unique_together={('part_number', 'is_active')},
        ),
        migrations.AlterUniqueTogether(
            name='ssd',
            unique_together={('part_number', 'is_active')},
        ),
        migrations.AlterUniqueTogether(
            name='wifi',
            unique_together={('part_number', 'is_active')},
        ),
    ]
