# Generated by Django 3.1.1 on 2022-09-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descriptions', '0007_auto_20220828_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cables',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='Name_cables'),
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='Name_case'),
        ),
        migrations.AlterField(
            model_name='cooler',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='Name_cooler'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='Name_cpu'),
        ),
        migrations.AlterField(
            model_name='fan',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='Name_fan'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='Name_gpu'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='Name_hdd'),
        ),
        migrations.AlterField(
            model_name='mb',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='Name_mb'),
        ),
        migrations.AlterField(
            model_name='psu',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='Name_psu'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='Name_ram'),
        ),
        migrations.AlterField(
            model_name='soft',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='Name_soft'),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='Name_ssd'),
        ),
        migrations.AlterField(
            model_name='wifi',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='Name_wifi'),
        ),
    ]
