# Generated by Django 4.1.6 on 2023-03-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descriptions', '0008_auto_20220901_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case_other',
            name='case_2_с',
        ),
        migrations.RemoveField(
            model_name='case_other',
            name='case_3_с',
        ),
        migrations.RemoveField(
            model_name='case_other',
            name='case_5_с',
        ),
        migrations.RemoveField(
            model_name='case_other',
            name='case_ai_ru',
        ),
        migrations.RemoveField(
            model_name='case_other',
            name='case_ai_ua',
        ),
        migrations.RemoveField(
            model_name='case_other',
            name='case_cm',
        ),
        migrations.RemoveField(
            model_name='case_other',
            name='case_color_ru',
        ),
        migrations.RemoveField(
            model_name='case_other',
            name='case_color_ua',
        ),
        migrations.RemoveField(
            model_name='case_other',
            name='case_df',
        ),
        migrations.RemoveField(
            model_name='case_other',
            name='case_e_с',
        ),
        migrations.RemoveField(
            model_name='case_other',
            name='case_fan_b',
        ),
        migrations.RemoveField(
            model_name='case_other',
            name='case_fan_f',
        ),
        migrations.RemoveField(
            model_name='case_other',
            name='case_fan_t',
        ),
        migrations.RemoveField(
            model_name='case_other',
            name='case_fp_m_ru',
        ),
        migrations.RemoveField(
            model_name='case_other',
            name='case_fp_m_ua',
        ),
        migrations.RemoveField(
            model_name='case_other',
            name='case_front_h',
        ),
        migrations.RemoveField(
            model_name='case_other',
            name='case_front_l',
        ),
        migrations.RemoveField(
            model_name='case_other',
            name='case_front_m',
        ),
        migrations.RemoveField(
            model_name='case_other',
            name='case_front_usb',
        ),
        migrations.RemoveField(
            model_name='case_other',
            name='case_max_cpu',
        ),
        migrations.RemoveField(
            model_name='case_other',
            name='case_max_gpu',
        ),
        migrations.RemoveField(
            model_name='case_other',
            name='case_os_ru',
        ),
        migrations.RemoveField(
            model_name='case_other',
            name='case_os_ua',
        ),
        migrations.RemoveField(
            model_name='case_other',
            name='case_pan_b',
        ),
        migrations.RemoveField(
            model_name='case_other',
            name='case_pan_f',
        ),
        migrations.RemoveField(
            model_name='case_other',
            name='case_pan_t',
        ),
        migrations.RemoveField(
            model_name='case_other',
            name='case_sh_m_ru',
        ),
        migrations.RemoveField(
            model_name='case_other',
            name='case_sh_m_ua',
        ),
        migrations.RemoveField(
            model_name='case_other',
            name='case_size',
        ),
        migrations.RemoveField(
            model_name='case_other',
            name='case_weight',
        ),
        migrations.RemoveField(
            model_name='cooler_other',
            name='cool_ai_ru',
        ),
        migrations.RemoveField(
            model_name='cooler_other',
            name='cool_ai_ua',
        ),
        migrations.RemoveField(
            model_name='cooler_other',
            name='cool_col',
        ),
        migrations.RemoveField(
            model_name='cooler_other',
            name='cool_conn',
        ),
        migrations.RemoveField(
            model_name='cooler_other',
            name='cool_fan_am',
        ),
        migrations.RemoveField(
            model_name='cooler_other',
            name='cool_fan_b_t_ru',
        ),
        migrations.RemoveField(
            model_name='cooler_other',
            name='cool_fan_b_t_ua',
        ),
        migrations.RemoveField(
            model_name='cooler_other',
            name='cool_fan_max_af',
        ),
        migrations.RemoveField(
            model_name='cooler_other',
            name='cool_fan_max_spd_ru',
        ),
        migrations.RemoveField(
            model_name='cooler_other',
            name='cool_fan_max_spd_ua',
        ),
        migrations.RemoveField(
            model_name='cooler_other',
            name='cool_fan_min_spd_ru',
        ),
        migrations.RemoveField(
            model_name='cooler_other',
            name='cool_fan_min_spd_ua',
        ),
        migrations.RemoveField(
            model_name='cooler_other',
            name='cool_fix_ru',
        ),
        migrations.RemoveField(
            model_name='cooler_other',
            name='cool_fix_ua',
        ),
        migrations.RemoveField(
            model_name='cooler_other',
            name='cool_min_no',
        ),
        migrations.RemoveField(
            model_name='cooler_other',
            name='cool_pwm',
        ),
        migrations.RemoveField(
            model_name='cooler_other',
            name='cool_rad_mat_ru',
        ),
        migrations.RemoveField(
            model_name='cooler_other',
            name='cool_rad_mat_ua',
        ),
        migrations.RemoveField(
            model_name='cooler_other',
            name='cool_tub_con_ru',
        ),
        migrations.RemoveField(
            model_name='cooler_other',
            name='cool_tub_con_ua',
        ),
        migrations.RemoveField(
            model_name='cooler_other',
            name='cool_w',
        ),
        migrations.RemoveField(
            model_name='cpu_other',
            name='cpu_ai_ru',
        ),
        migrations.RemoveField(
            model_name='cpu_other',
            name='cpu_ai_ua',
        ),
        migrations.RemoveField(
            model_name='cpu_other',
            name='cpu_bot',
        ),
        migrations.RemoveField(
            model_name='cpu_other',
            name='cpu_cha',
        ),
        migrations.RemoveField(
            model_name='cpu_other',
            name='cpu_core_name',
        ),
        migrations.RemoveField(
            model_name='cpu_other',
            name='cpu_fam',
        ),
        migrations.RemoveField(
            model_name='cpu_other',
            name='cpu_gpu_model',
        ),
        migrations.RemoveField(
            model_name='cpu_other',
            name='cpu_max_ram',
        ),
        migrations.RemoveField(
            model_name='cpu_other',
            name='cpu_max_temp',
        ),
        migrations.RemoveField(
            model_name='cpu_other',
            name='cpu_nm',
        ),
        migrations.RemoveField(
            model_name='cpu_other',
            name='cpu_tdp',
        ),
        migrations.RemoveField(
            model_name='fan_other',
            name='fan_ai_ru',
        ),
        migrations.RemoveField(
            model_name='fan_other',
            name='fan_ai_ua',
        ),
        migrations.RemoveField(
            model_name='fan_other',
            name='fan_max_af',
        ),
        migrations.RemoveField(
            model_name='fan_other',
            name='fan_max_spd_ru',
        ),
        migrations.RemoveField(
            model_name='fan_other',
            name='fan_max_spd_ua',
        ),
        migrations.RemoveField(
            model_name='fan_other',
            name='fan_min_spd_ru',
        ),
        migrations.RemoveField(
            model_name='fan_other',
            name='fan_min_spd_ua',
        ),
        migrations.RemoveField(
            model_name='fan_other',
            name='fan_pwm',
        ),
        migrations.RemoveField(
            model_name='gpu_other',
            name='gpu_ai_ru',
        ),
        migrations.RemoveField(
            model_name='gpu_other',
            name='gpu_ai_ua',
        ),
        migrations.RemoveField(
            model_name='gpu_other',
            name='gpu_cool_ru',
        ),
        migrations.RemoveField(
            model_name='gpu_other',
            name='gpu_cool_ua',
        ),
        migrations.RemoveField(
            model_name='gpu_other',
            name='gpu_lp',
        ),
        migrations.RemoveField(
            model_name='gpu_other',
            name='gpu_max_sc',
        ),
        migrations.RemoveField(
            model_name='gpu_other',
            name='gpu_mem_type',
        ),
        migrations.RemoveField(
            model_name='gpu_other',
            name='gpu_model',
        ),
        migrations.RemoveField(
            model_name='gpu_other',
            name='gpu_sl',
        ),
        migrations.RemoveField(
            model_name='gpu_other',
            name='gpu_watt',
        ),
        migrations.RemoveField(
            model_name='hdd_other',
            name='hdd_ai_ru',
        ),
        migrations.RemoveField(
            model_name='hdd_other',
            name='hdd_ai_ua',
        ),
        migrations.RemoveField(
            model_name='hdd_other',
            name='hdd_int',
        ),
        migrations.RemoveField(
            model_name='hdd_other',
            name='hdd_type1_ru',
        ),
        migrations.RemoveField(
            model_name='hdd_other',
            name='hdd_type1_ua',
        ),
        migrations.RemoveField(
            model_name='hdd_other',
            name='hdd_type2_ru',
        ),
        migrations.RemoveField(
            model_name='hdd_other',
            name='hdd_type2_ua',
        ),
        migrations.RemoveField(
            model_name='mb_other',
            name='part_mb_ai_ru',
        ),
        migrations.RemoveField(
            model_name='mb_other',
            name='part_mb_ai_ua',
        ),
        migrations.RemoveField(
            model_name='mb_other',
            name='part_mb_cpu_conn',
        ),
        migrations.RemoveField(
            model_name='mb_other',
            name='part_mb_fan_conn',
        ),
        migrations.RemoveField(
            model_name='mb_other',
            name='part_mb_lan_chip',
        ),
        migrations.RemoveField(
            model_name='mb_other',
            name='part_mb_main_conn',
        ),
        migrations.RemoveField(
            model_name='mb_other',
            name='part_mb_pow_ph',
        ),
        migrations.RemoveField(
            model_name='mb_other',
            name='part_mb_ram_ch',
        ),
        migrations.RemoveField(
            model_name='mb_other',
            name='part_mb_ram_sl',
        ),
        migrations.RemoveField(
            model_name='mb_other',
            name='part_mb_ram_type',
        ),
        migrations.RemoveField(
            model_name='mb_other',
            name='part_mb_sl_x1',
        ),
        migrations.RemoveField(
            model_name='mb_other',
            name='part_mb_sl_x16',
        ),
        migrations.RemoveField(
            model_name='mb_other',
            name='part_mb_sound_ch',
        ),
        migrations.RemoveField(
            model_name='mb_other',
            name='part_mb_sound_chip',
        ),
        migrations.RemoveField(
            model_name='psu_other',
            name='psu_ai_ru',
        ),
        migrations.RemoveField(
            model_name='psu_other',
            name='psu_ai_ua',
        ),
        migrations.RemoveField(
            model_name='psu_other',
            name='psu_gpu_conn',
        ),
        migrations.RemoveField(
            model_name='psu_other',
            name='psu_main_conn',
        ),
        migrations.RemoveField(
            model_name='psu_other',
            name='psu_mod_ru',
        ),
        migrations.RemoveField(
            model_name='psu_other',
            name='psu_mod_ua',
        ),
        migrations.RemoveField(
            model_name='psu_other',
            name='psu_molex_conn',
        ),
        migrations.RemoveField(
            model_name='psu_other',
            name='psu_no',
        ),
        migrations.RemoveField(
            model_name='psu_other',
            name='psu_pfc',
        ),
        migrations.RemoveField(
            model_name='psu_other',
            name='psu_sata_conn',
        ),
        migrations.RemoveField(
            model_name='psu_other',
            name='psu_sl',
        ),
        migrations.RemoveField(
            model_name='ram_other',
            name='ram_ai_ru',
        ),
        migrations.RemoveField(
            model_name='ram_other',
            name='ram_ai_ua',
        ),
        migrations.RemoveField(
            model_name='ram_other',
            name='ram_cl',
        ),
        migrations.RemoveField(
            model_name='ram_other',
            name='ram_cool_ru',
        ),
        migrations.RemoveField(
            model_name='ram_other',
            name='ram_cool_ua',
        ),
        migrations.RemoveField(
            model_name='ram_other',
            name='ram_led',
        ),
        migrations.RemoveField(
            model_name='ram_other',
            name='ram_pow',
        ),
        migrations.RemoveField(
            model_name='ram_other',
            name='ram_type',
        ),
        migrations.RemoveField(
            model_name='ram_other',
            name='ram_xmp',
        ),
        migrations.RemoveField(
            model_name='ssd_other',
            name='ssd_ai_ru',
        ),
        migrations.RemoveField(
            model_name='ssd_other',
            name='ssd_ai_ua',
        ),
        migrations.RemoveField(
            model_name='ssd_other',
            name='ssd_con_type',
        ),
        migrations.RemoveField(
            model_name='ssd_other',
            name='ssd_type1_ru',
        ),
        migrations.RemoveField(
            model_name='ssd_other',
            name='ssd_type1_ua',
        ),
        migrations.RemoveField(
            model_name='ssd_other',
            name='ssd_type2_ru',
        ),
        migrations.RemoveField(
            model_name='ssd_other',
            name='ssd_type2_ua',
        ),
        migrations.AddField(
            model_name='cables',
            name='config',
            field=models.BooleanField(default=True, verbose_name='конфигуратор/нет'),
        ),
        migrations.AddField(
            model_name='case',
            name='case_count_fan',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('4+', '4+')], db_index=True, max_length=50, null=True, verbose_name='Кол вентиляторов'),
        ),
        migrations.AddField(
            model_name='case',
            name='case_gpu_triple_fan_ru',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет')], db_index=True, max_length=50, null=True, verbose_name='3х куллерная карта(ру)'),
        ),
        migrations.AddField(
            model_name='case',
            name='case_gpu_triple_fan_ua',
            field=models.CharField(blank=True, choices=[('Так', 'Так'), ('Нi', 'Нi')], db_index=True, max_length=50, null=True, verbose_name='3х куллерная карта(укр)'),
        ),
        migrations.AddField(
            model_name='case',
            name='case_wcs_plus_size_ru',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет')], db_index=True, max_length=50, null=True, verbose_name='360мм СВО(ру)'),
        ),
        migrations.AddField(
            model_name='case',
            name='case_wcs_plus_size_ua',
            field=models.CharField(blank=True, choices=[('Так', 'Так'), ('Нi', 'Нi')], db_index=True, max_length=50, null=True, verbose_name='360мм СВО(укр)'),
        ),
        migrations.AddField(
            model_name='case',
            name='config',
            field=models.BooleanField(default=True, verbose_name='конфигуратор/нет'),
        ),
        migrations.AddField(
            model_name='case_other',
            name='case_fan',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='кол предустановленных вентиляторов'),
        ),
        migrations.AddField(
            model_name='case_other',
            name='case_mb',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='форм-фактор мат. платы'),
        ),
        migrations.AddField(
            model_name='case_other',
            name='case_rgb',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='подсветка'),
        ),
        migrations.AddField(
            model_name='cooler',
            name='config',
            field=models.BooleanField(default=True, verbose_name='конфигуратор/нет'),
        ),
        migrations.AddField(
            model_name='cooler',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='фото'),
        ),
        migrations.AddField(
            model_name='cooler',
            name='fan_triple_wcs_rus',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет')], db_index=True, max_length=50, null=True, verbose_name='СВО 3х куллерная(ру)'),
        ),
        migrations.AddField(
            model_name='cooler',
            name='fan_triple_wcs_ua',
            field=models.CharField(blank=True, choices=[('Так', 'Так'), ('Нi', 'Нi')], db_index=True, max_length=50, null=True, verbose_name='СВО 3х куллерная(укр)'),
        ),
        migrations.AddField(
            model_name='cooler_other',
            name='cool_col_ru',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='цвет ру'),
        ),
        migrations.AddField(
            model_name='cooler_other',
            name='cool_col_ua',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='цвет укр'),
        ),
        migrations.AddField(
            model_name='cooler_other',
            name='cool_rgb',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='подсветка'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='config',
            field=models.BooleanField(default=True, verbose_name='конфигуратор/нет'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='cpu_render_ru',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], db_index=True, default='Нет', max_length=50, verbose_name='пригодность для рендера'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='cpu_render_ukr',
            field=models.CharField(choices=[('Так', 'Так'), ('Нi', 'Нi')], db_index=True, default='Нi', max_length=50, verbose_name='пригодность для рендера(укр)'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='cpu_streem_ru',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], db_index=True, default='Нет', max_length=50, verbose_name='пригодность для стриминга'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='cpu_streem_ukr',
            field=models.CharField(choices=[('Так', 'Так'), ('Нi', 'Нi')], db_index=True, default='Нi', max_length=50, verbose_name='пригодность для стриминга(укр)'),
        ),
        migrations.AddField(
            model_name='fan',
            name='config',
            field=models.BooleanField(default=True, verbose_name='конфигуратор/нет'),
        ),
        migrations.AddField(
            model_name='fan_other',
            name='fan_col_ru',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='цвет ру'),
        ),
        migrations.AddField(
            model_name='fan_other',
            name='fan_col_ua',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='цвет укр'),
        ),
        migrations.AddField(
            model_name='fan_other',
            name='fan_quantity',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='кол в наборе'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='config',
            field=models.BooleanField(default=True, verbose_name='конфигуратор/нет'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='gpu_3d_ru',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], db_index=True, default='Нет', max_length=50, verbose_name='пригодность для 3D мод'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='gpu_3d_ukr',
            field=models.CharField(choices=[('Так', 'Так'), ('Нi', 'Нi')], db_index=True, default='Нi', max_length=50, verbose_name='пригодность для 3D мод(укр)'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='gpu_VR_ru',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], db_index=True, default='Нет', max_length=50, verbose_name='пригодность для VR'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='gpu_VR_ukr',
            field=models.CharField(choices=[('Так', 'Так'), ('Нi', 'Нi')], db_index=True, default='Нi', max_length=50, verbose_name='пригодность для VR(укр)'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='gpu_ref_hd',
            field=models.CharField(choices=[('FullHD (1080p)', 'FullHD (1080p)'), ('QuadHD 2K (1440p)', 'QuadHD 2K (1440p)'), ('UltraHD 4K (2160p)', 'UltraHD 4K (2160p)')], db_index=True, default='FullHD (1080p)', max_length=300, verbose_name='рекомендуемое разрешение'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='gpu_triple_fan_rus',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет')], db_index=True, max_length=10, null=True, verbose_name='3х куллерная карта(ру)'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='gpu_triple_fan_ua',
            field=models.CharField(blank=True, choices=[('Так', 'Так'), ('Нi', 'Нi')], db_index=True, max_length=10, null=True, verbose_name='3х куллерная карта(укр)'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='gpu_type_ru',
            field=models.CharField(choices=[('Базовый Игровой', 'Базовый Игровой'), ('Продвинутый Игровой', 'Продвинутый Игровой'), ('Максимальный Игровой', 'Максимальный Игровой')], db_index=True, default='Продвинутый Игровой', max_length=50, verbose_name='игровое назначение(ру)'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='gpu_type_ukr',
            field=models.CharField(choices=[('Базовий Ігровий', 'Базовий Ігровий'), ('Прогресивний Ігровий', 'Прогресивний Ігровий'), ('Максимальний Ігровий', 'Максимальний Ігровий')], db_index=True, default='Прогресивний Ігровий', max_length=50, verbose_name='игровое назначение(укр)'),
        ),
        migrations.AddField(
            model_name='gpu_other',
            name='gpu_fan',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='кол вентиляторов'),
        ),
        migrations.AddField(
            model_name='hdd',
            name='config',
            field=models.BooleanField(default=True, verbose_name='конфигуратор/нет'),
        ),
        migrations.AddField(
            model_name='mb',
            name='config',
            field=models.BooleanField(default=True, verbose_name='конфигуратор/нет'),
        ),
        migrations.AddField(
            model_name='mb',
            name='mb_count_slot',
            field=models.CharField(blank=True, choices=[('2', '2'), ('4', '4'), ('8', '8')], db_index=True, max_length=50, null=True, verbose_name='кол слотов памяти'),
        ),
        migrations.AddField(
            model_name='mb',
            name='mb_type_memory',
            field=models.CharField(blank=True, choices=[('DDR3', 'DDR3'), ('DDR4', 'DDR4'), ('DDR5', 'DDR5')], db_index=True, max_length=50, null=True, verbose_name='тип памяти'),
        ),
        migrations.AddField(
            model_name='mb_other',
            name='part_mb_ff',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='форм-фактор'),
        ),
        migrations.AddField(
            model_name='mb_other',
            name='part_mb_rgb_header',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='RGB Header'),
        ),
        migrations.AddField(
            model_name='mb_other',
            name='part_mb_usb_type_c',
            field=models.CharField(choices=[('+', '+'), ('-', '-')], db_index=True, default='+', max_length=30, verbose_name='USB Type-C'),
        ),
        migrations.AddField(
            model_name='psu',
            name='config',
            field=models.BooleanField(default=True, verbose_name='конфигуратор/нет'),
        ),
        migrations.AddField(
            model_name='ram',
            name='config',
            field=models.BooleanField(default=True, verbose_name='конфигуратор/нет'),
        ),
        migrations.AddField(
            model_name='ram',
            name='depend_from',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='depend_from'),
        ),
        migrations.AddField(
            model_name='ram',
            name='depend_from_type',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='depend_from_type'),
        ),
        migrations.AddField(
            model_name='ram',
            name='depend_to',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='depend_to'),
        ),
        migrations.AddField(
            model_name='ram',
            name='depend_to_type',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='depend_to_type'),
        ),
        migrations.AddField(
            model_name='ram',
            name='mem_type',
            field=models.CharField(blank=True, choices=[('DDR3', 'DDR3'), ('DDR4', 'DDR4'), ('DDR5', 'DDR5')], db_index=True, max_length=50, null=True, verbose_name='тип памяти'),
        ),
        migrations.AddField(
            model_name='soft',
            name='config',
            field=models.BooleanField(default=True, verbose_name='конфигуратор/нет'),
        ),
        migrations.AddField(
            model_name='ssd',
            name='config',
            field=models.BooleanField(default=True, verbose_name='конфигуратор/нет'),
        ),
        migrations.AddField(
            model_name='wifi',
            name='config',
            field=models.BooleanField(default=True, verbose_name='конфигуратор/нет'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_s',
            field=models.CharField(db_index=True, max_length=300, verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='case',
            name='color_ru',
            field=models.CharField(blank=True, db_index=True, default='', max_length=300, null=True, verbose_name='цвет ру'),
        ),
        migrations.AlterField(
            model_name='case',
            name='color_ukr',
            field=models.CharField(blank=True, db_index=True, default='', max_length=300, null=True, verbose_name='цвет укр'),
        ),
        migrations.AlterField(
            model_name='case',
            name='desc_ru',
            field=models.TextField(db_index=True, verbose_name='описание_ру'),
        ),
        migrations.AlterField(
            model_name='case',
            name='desc_ukr',
            field=models.TextField(db_index=True, verbose_name='описание_укр_ukr'),
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='case',
            name='part_number',
            field=models.CharField(db_index=True, max_length=300, verbose_name='партнамбер'),
        ),
        migrations.AlterField(
            model_name='case',
            name='price',
            field=models.FloatField(db_index=True, max_length=300, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='case',
            name='vendor',
            field=models.CharField(db_index=True, max_length=300, verbose_name='производитель'),
        ),
        migrations.AlterField(
            model_name='case_other',
            name='case_psu_p',
            field=models.CharField(choices=[('+', '+'), ('-', '-')], db_index=True, default='+', max_length=30, verbose_name='блок питания (есть/нету)'),
        ),
        migrations.AlterField(
            model_name='case_other',
            name='case_psu_w_ru',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='отсек для БП ру'),
        ),
        migrations.AlterField(
            model_name='case_other',
            name='case_psu_w_ua',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='отсек для БП укр'),
        ),
        migrations.AlterField(
            model_name='case_other',
            name='case_sp_m_ru',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='боковое окно ру'),
        ),
        migrations.AlterField(
            model_name='case_other',
            name='case_sp_m_ua',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='боковое окно укр'),
        ),
        migrations.AlterField(
            model_name='case_other',
            name='case_warr_ru',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='гарантия_ру'),
        ),
        migrations.AlterField(
            model_name='case_other',
            name='case_warr_ua',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='гарантия_укр'),
        ),
        migrations.AlterField(
            model_name='case_other',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Одиночная деталь вкл/выкл'),
        ),
        migrations.AlterField(
            model_name='cooler',
            name='cooler_height',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='высота кулера'),
        ),
        migrations.AlterField(
            model_name='cooler',
            name='desc_ru',
            field=models.TextField(db_index=True, verbose_name='описание_ру'),
        ),
        migrations.AlterField(
            model_name='cooler',
            name='desc_ukr',
            field=models.TextField(db_index=True, verbose_name='описание_укр'),
        ),
        migrations.AlterField(
            model_name='cooler',
            name='fan_noise_level',
            field=models.CharField(db_index=True, max_length=300, verbose_name='уровень шума'),
        ),
        migrations.AlterField(
            model_name='cooler',
            name='fan_size',
            field=models.CharField(db_index=True, max_length=300, verbose_name='диаметр'),
        ),
        migrations.AlterField(
            model_name='cooler',
            name='fan_spd_rus',
            field=models.CharField(db_index=True, max_length=300, verbose_name='скорость вращения (max)ру'),
        ),
        migrations.AlterField(
            model_name='cooler',
            name='fan_spd_ua',
            field=models.CharField(db_index=True, max_length=300, verbose_name='скорость вращения (max)укр'),
        ),
        migrations.AlterField(
            model_name='cooler',
            name='fan_type_rus',
            field=models.CharField(db_index=True, max_length=300, verbose_name='тип кулера ру'),
        ),
        migrations.AlterField(
            model_name='cooler',
            name='fan_type_ua',
            field=models.CharField(db_index=True, max_length=300, verbose_name='тип кулера укр'),
        ),
        migrations.AlterField(
            model_name='cooler',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='cooler',
            name='part_number',
            field=models.CharField(db_index=True, max_length=300, verbose_name='партнамбер'),
        ),
        migrations.AlterField(
            model_name='cooler',
            name='price',
            field=models.FloatField(db_index=True, max_length=300, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='cooler',
            name='vendor',
            field=models.CharField(db_index=True, max_length=300, verbose_name='производитель'),
        ),
        migrations.AlterField(
            model_name='cooler_other',
            name='cool_h',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='высота кулера'),
        ),
        migrations.AlterField(
            model_name='cooler_other',
            name='cool_max_tdp',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='максимальное TDP'),
        ),
        migrations.AlterField(
            model_name='cooler_other',
            name='cool_sock',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='сокет'),
        ),
        migrations.AlterField(
            model_name='cooler_other',
            name='cool_tub_am',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='кол тепловых труб'),
        ),
        migrations.AlterField(
            model_name='cooler_other',
            name='cool_warr_ru',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='гарантия ру'),
        ),
        migrations.AlterField(
            model_name='cooler_other',
            name='cool_warr_ua',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='гарантия укр'),
        ),
        migrations.AlterField(
            model_name='cooler_other',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Одиночная деталь вкл/выкл'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cpu_b_f',
            field=models.CharField(db_index=True, max_length=300, verbose_name='тактовая частота'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cpu_c_t',
            field=models.CharField(db_index=True, max_length=300, verbose_name='ядра/потоки'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cpu_cache',
            field=models.CharField(db_index=True, max_length=300, verbose_name='кеш'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cpu_i_g_rus',
            field=models.CharField(db_index=True, max_length=300, verbose_name='графика_ру'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cpu_i_g_ua',
            field=models.CharField(db_index=True, max_length=300, verbose_name='графика_укр'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='desc_ru',
            field=models.TextField(db_index=True, verbose_name='описание_ру'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='desc_ukr',
            field=models.TextField(db_index=True, verbose_name='описание_укр'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='f_name',
            field=models.CharField(db_index=True, max_length=300, verbose_name='линейка'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='part_number',
            field=models.CharField(db_index=True, max_length=300, verbose_name='партнамбер'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='price',
            field=models.FloatField(db_index=True, max_length=300, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='vendor',
            field=models.CharField(db_index=True, max_length=300, verbose_name='производитель'),
        ),
        migrations.AlterField(
            model_name='cpu_other',
            name='cpu_core',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='кол ядер'),
        ),
        migrations.AlterField(
            model_name='cpu_other',
            name='cpu_gpu',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='графика'),
        ),
        migrations.AlterField(
            model_name='cpu_other',
            name='cpu_soc',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='тип разъема (Socket)'),
        ),
        migrations.AlterField(
            model_name='cpu_other',
            name='cpu_tbfq',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='тактовая частота (max)'),
        ),
        migrations.AlterField(
            model_name='cpu_other',
            name='cpu_threeds',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='кол потоков'),
        ),
        migrations.AlterField(
            model_name='cpu_other',
            name='cpu_warr_ru',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='гарантия ру'),
        ),
        migrations.AlterField(
            model_name='cpu_other',
            name='cpu_warr_ua',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='гарантия укр'),
        ),
        migrations.AlterField(
            model_name='cpu_other',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Одиночная деталь вкл/выкл'),
        ),
        migrations.AlterField(
            model_name='fan',
            name='case_fan_noise_level',
            field=models.CharField(db_index=True, max_length=300, verbose_name='уровень шума'),
        ),
        migrations.AlterField(
            model_name='fan',
            name='case_fan_size',
            field=models.CharField(db_index=True, max_length=300, verbose_name='диаметр'),
        ),
        migrations.AlterField(
            model_name='fan',
            name='case_fan_spd_rus',
            field=models.CharField(db_index=True, max_length=300, verbose_name='скорость вращения ру(max)'),
        ),
        migrations.AlterField(
            model_name='fan',
            name='case_fan_spd_ua',
            field=models.CharField(db_index=True, max_length=300, verbose_name='скорость вращения укр(max)'),
        ),
        migrations.AlterField(
            model_name='fan',
            name='desc_ru',
            field=models.TextField(db_index=True, verbose_name='описание_ру'),
        ),
        migrations.AlterField(
            model_name='fan',
            name='desc_ukr',
            field=models.TextField(db_index=True, verbose_name='описание_укр'),
        ),
        migrations.AlterField(
            model_name='fan',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='fan',
            name='part_number',
            field=models.CharField(db_index=True, max_length=300, verbose_name='партнамбер'),
        ),
        migrations.AlterField(
            model_name='fan',
            name='price',
            field=models.FloatField(db_index=True, max_length=300, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='fan',
            name='vendor',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='производитель'),
        ),
        migrations.AlterField(
            model_name='fan_other',
            name='fan_b_type_ru',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='Тип подшипника ру'),
        ),
        migrations.AlterField(
            model_name='fan_other',
            name='fan_b_type_ua',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='тип подшипника укр'),
        ),
        migrations.AlterField(
            model_name='fan_other',
            name='fan_led_type_ru',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='подсветка ру'),
        ),
        migrations.AlterField(
            model_name='fan_other',
            name='fan_led_type_ua',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='подсветка укр'),
        ),
        migrations.AlterField(
            model_name='fan_other',
            name='fan_pow',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='подключение'),
        ),
        migrations.AlterField(
            model_name='fan_other',
            name='fan_warr_ru',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='гарантия_ру'),
        ),
        migrations.AlterField(
            model_name='fan_other',
            name='fan_warr_ua',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='гарантия_укр'),
        ),
        migrations.AlterField(
            model_name='fan_other',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Одиночная деталь вкл/выкл'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='desc_ru',
            field=models.TextField(db_index=True, verbose_name='описание_ру'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='desc_ukr',
            field=models.TextField(db_index=True, verbose_name='описание_укр'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='f_name',
            field=models.CharField(db_index=True, max_length=300, verbose_name='чип'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='gpu_b',
            field=models.CharField(db_index=True, max_length=300, verbose_name='разрядность'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='gpu_m_s',
            field=models.CharField(db_index=True, max_length=300, verbose_name='объём памяти'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='main_category',
            field=models.CharField(db_index=True, max_length=300, verbose_name='семейство процессора'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='part_number',
            field=models.CharField(db_index=True, max_length=300, verbose_name='партнамбер'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='price',
            field=models.FloatField(db_index=True, max_length=300, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='vendor',
            field=models.CharField(db_index=True, max_length=300, verbose_name='производитель'),
        ),
        migrations.AlterField(
            model_name='gpu_other',
            name='gpu_dp',
            field=models.CharField(choices=[('+', '+'), ('-', '-')], db_index=True, default='+', max_length=300, verbose_name='разъемы_dp'),
        ),
        migrations.AlterField(
            model_name='gpu_other',
            name='gpu_dvi',
            field=models.CharField(choices=[('+', '+'), ('-', '-')], db_index=True, default='+', max_length=300, verbose_name='разъемы_dvi'),
        ),
        migrations.AlterField(
            model_name='gpu_other',
            name='gpu_hdmi',
            field=models.CharField(choices=[('+', '+'), ('-', '-')], db_index=True, default='+', max_length=300, verbose_name='разъемы_hdmi'),
        ),
        migrations.AlterField(
            model_name='gpu_other',
            name='gpu_max_l',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='длина видеокарты'),
        ),
        migrations.AlterField(
            model_name='gpu_other',
            name='gpu_vga',
            field=models.CharField(choices=[('+', '+'), ('-', '-')], db_index=True, default='+', max_length=300, verbose_name='разъемы_vga'),
        ),
        migrations.AlterField(
            model_name='gpu_other',
            name='gpu_warr_ru',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='гарантия_ру'),
        ),
        migrations.AlterField(
            model_name='gpu_other',
            name='gpu_warr_ua',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='гарантия_укр'),
        ),
        migrations.AlterField(
            model_name='gpu_other',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Одиночная деталь вкл/выкл'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='desc_ru',
            field=models.TextField(db_index=True, verbose_name='описание_ру'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='desc_ukr',
            field=models.TextField(db_index=True, verbose_name='описание_укр'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='f_name',
            field=models.CharField(db_index=True, max_length=300, verbose_name='объем памяти'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='hdd_ca',
            field=models.CharField(db_index=True, max_length=300, verbose_name='буфер обмена'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='hdd_spd_rus',
            field=models.CharField(db_index=True, max_length=300, verbose_name='скорость вращения ру'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='hdd_spd_ua',
            field=models.CharField(db_index=True, max_length=300, verbose_name='скорость вращения укр'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='part_number',
            field=models.CharField(db_index=True, max_length=300, verbose_name='партнамбер'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='price',
            field=models.FloatField(db_index=True, max_length=300, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='vendor',
            field=models.CharField(db_index=True, max_length=300, verbose_name='производитель'),
        ),
        migrations.AlterField(
            model_name='hdd_other',
            name='hdd_ff',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='форм-фактор'),
        ),
        migrations.AlterField(
            model_name='hdd_other',
            name='hdd_warr_ru',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='гарантия_ру'),
        ),
        migrations.AlterField(
            model_name='hdd_other',
            name='hdd_warr_ua',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='гарантия_укр'),
        ),
        migrations.AlterField(
            model_name='hdd_other',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Одиночная деталь вкл/выкл'),
        ),
        migrations.AlterField(
            model_name='mb',
            name='desc_ru',
            field=models.TextField(db_index=True, verbose_name='описание_ру'),
        ),
        migrations.AlterField(
            model_name='mb',
            name='desc_ukr',
            field=models.TextField(db_index=True, verbose_name='описание_укр'),
        ),
        migrations.AlterField(
            model_name='mb',
            name='main_category',
            field=models.CharField(db_index=True, max_length=300, verbose_name='для процессоров'),
        ),
        migrations.AlterField(
            model_name='mb',
            name='mb_chipset',
            field=models.CharField(db_index=True, max_length=300, verbose_name='чипсет'),
        ),
        migrations.AlterField(
            model_name='mb',
            name='mb_max_ram',
            field=models.CharField(db_index=True, max_length=300, verbose_name='макс. объем памяти'),
        ),
        migrations.AlterField(
            model_name='mb',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='mb',
            name='part_number',
            field=models.CharField(db_index=True, max_length=300, verbose_name='партнамбер'),
        ),
        migrations.AlterField(
            model_name='mb',
            name='price',
            field=models.FloatField(db_index=True, max_length=300, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='mb',
            name='vendor',
            field=models.CharField(db_index=True, max_length=300, verbose_name='производитель'),
        ),
        migrations.AlterField(
            model_name='mb_other',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Одиночная деталь вкл/выкл'),
        ),
        migrations.AlterField(
            model_name='mb_other',
            name='part_mb_bt',
            field=models.CharField(choices=[('+', '+'), ('-', '-')], db_index=True, default='+', max_length=30, verbose_name='разьем_bluetooth'),
        ),
        migrations.AlterField(
            model_name='mb_other',
            name='part_mb_dp',
            field=models.CharField(choices=[('+', '+'), ('-', '-')], db_index=True, default='+', max_length=30, verbose_name='видеовыход_dp'),
        ),
        migrations.AlterField(
            model_name='mb_other',
            name='part_mb_dvi',
            field=models.CharField(choices=[('+', '+'), ('-', '-')], db_index=True, default='+', max_length=30, verbose_name='видеовыход_dvi'),
        ),
        migrations.AlterField(
            model_name='mb_other',
            name='part_mb_hdmi',
            field=models.CharField(choices=[('+', '+'), ('-', '-')], db_index=True, default='+', max_length=30, verbose_name='видеовыход_hdmi'),
        ),
        migrations.AlterField(
            model_name='mb_other',
            name='part_mb_lan',
            field=models.CharField(choices=[('+', '+'), ('-', '-')], db_index=True, default='+', max_length=30, verbose_name='разьем_lan'),
        ),
        migrations.AlterField(
            model_name='mb_other',
            name='part_mb_m2',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='кол M.2'),
        ),
        migrations.AlterField(
            model_name='mb_other',
            name='part_mb_raid',
            field=models.CharField(choices=[('+', '+'), ('-', '-')], db_index=True, default=True, max_length=30, verbose_name='наличие_raid'),
        ),
        migrations.AlterField(
            model_name='mb_other',
            name='part_mb_ram_max_spd',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='максимальная частота ОЗУ'),
        ),
        migrations.AlterField(
            model_name='mb_other',
            name='part_mb_sata',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='кол SATA'),
        ),
        migrations.AlterField(
            model_name='mb_other',
            name='part_mb_sock',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='тип разъема (Socket)'),
        ),
        migrations.AlterField(
            model_name='mb_other',
            name='part_mb_vga',
            field=models.CharField(choices=[('+', '+'), ('-', '-')], db_index=True, default='+', max_length=30, verbose_name='видеовыход_vga'),
        ),
        migrations.AlterField(
            model_name='mb_other',
            name='part_mb_warr_ru',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='гарантия_ru'),
        ),
        migrations.AlterField(
            model_name='mb_other',
            name='part_mb_warr_ua',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='гарантия_ua'),
        ),
        migrations.AlterField(
            model_name='mb_other',
            name='part_mb_wifi',
            field=models.CharField(choices=[('+', '+'), ('-', '-')], db_index=True, default='+', max_length=30, verbose_name='разьем_wifi'),
        ),
        migrations.AlterField(
            model_name='psu',
            name='desc_ru',
            field=models.TextField(db_index=True, verbose_name='описание_ру'),
        ),
        migrations.AlterField(
            model_name='psu',
            name='desc_ukr',
            field=models.TextField(db_index=True, verbose_name='описание_укр'),
        ),
        migrations.AlterField(
            model_name='psu',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='psu',
            name='part_number',
            field=models.CharField(db_index=True, max_length=300, verbose_name='партнамбер'),
        ),
        migrations.AlterField(
            model_name='psu',
            name='price',
            field=models.FloatField(db_index=True, max_length=300, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='psu',
            name='psu_c',
            field=models.CharField(db_index=True, max_length=300, verbose_name='сертификация БП'),
        ),
        migrations.AlterField(
            model_name='psu',
            name='psu_f',
            field=models.CharField(db_index=True, max_length=300, verbose_name='вентиляторы'),
        ),
        migrations.AlterField(
            model_name='psu',
            name='psu_p',
            field=models.CharField(db_index=True, max_length=300, verbose_name='мощность'),
        ),
        migrations.AlterField(
            model_name='psu',
            name='vendor',
            field=models.CharField(db_index=True, max_length=300, verbose_name='производитель'),
        ),
        migrations.AlterField(
            model_name='psu_other',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Одиночная деталь вкл/выкл'),
        ),
        migrations.AlterField(
            model_name='psu_other',
            name='psu_ff',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='форм-фактор'),
        ),
        migrations.AlterField(
            model_name='psu_other',
            name='psu_warr_ru',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='гарантия_ру'),
        ),
        migrations.AlterField(
            model_name='psu_other',
            name='psu_warr_ua',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='гарантия_укр'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='desc_ru',
            field=models.TextField(db_index=True, verbose_name='описание_ру'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='desc_ukr',
            field=models.TextField(db_index=True, verbose_name='описание_укр'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='f_name',
            field=models.CharField(db_index=True, max_length=300, verbose_name='объём памяти'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='mem_spd',
            field=models.CharField(db_index=True, max_length=300, verbose_name='частота памяти'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='part_number',
            field=models.CharField(db_index=True, max_length=300, verbose_name='партнамбер'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='price',
            field=models.FloatField(db_index=True, max_length=300, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='vendor',
            field=models.CharField(db_index=True, max_length=300, verbose_name='производитель'),
        ),
        migrations.AlterField(
            model_name='ram_other',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Одиночная деталь вкл/выкл'),
        ),
        migrations.AlterField(
            model_name='ram_other',
            name='ram_col_ru',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='цвет_ру'),
        ),
        migrations.AlterField(
            model_name='ram_other',
            name='ram_col_ua',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='цвет_укр'),
        ),
        migrations.AlterField(
            model_name='ram_other',
            name='ram_mod_am',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='кол модулей'),
        ),
        migrations.AlterField(
            model_name='ram_other',
            name='ram_warr_ru',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='гарантия_ру'),
        ),
        migrations.AlterField(
            model_name='ram_other',
            name='ram_warr_ua',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='гарантия_укр'),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='desc_ru',
            field=models.TextField(db_index=True, verbose_name='описание_ру'),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='desc_ukr',
            field=models.TextField(db_index=True, verbose_name='описание_укр'),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='f_name',
            field=models.CharField(db_index=True, max_length=300, verbose_name='объем памяти'),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='part_number',
            field=models.CharField(db_index=True, max_length=300, verbose_name='партнамбер'),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='ssd_type_cells',
            field=models.CharField(db_index=True, max_length=300, verbose_name='тип ячеек памяти'),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='vendor',
            field=models.CharField(db_index=True, max_length=300, verbose_name='производитель'),
        ),
        migrations.AlterField(
            model_name='ssd_other',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Одиночная деталь вкл/выкл'),
        ),
        migrations.AlterField(
            model_name='ssd_other',
            name='part_ssd_r_spd',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='скорость чтения'),
        ),
        migrations.AlterField(
            model_name='ssd_other',
            name='part_ssd_w_spd',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='скорость записи'),
        ),
        migrations.AlterField(
            model_name='ssd_other',
            name='ssd_ff',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='форм-фактор'),
        ),
        migrations.AlterField(
            model_name='ssd_other',
            name='ssd_int',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='интерфейс'),
        ),
        migrations.AlterField(
            model_name='ssd_other',
            name='ssd_warr_ru',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='гарантия_ру'),
        ),
        migrations.AlterField(
            model_name='ssd_other',
            name='ssd_warr_ua',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='гарантия_укр'),
        ),
    ]
