"""
Django settings for sereja project.

Generated by 'django-admin startproject' using Django 3.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = '@r+%6h(6pu-yszhl=k)^g5@=yq8n_0xa6pd)qr=jg=+@-on&*n'
SECRET_KEY = os.environ.get('SECRET_KEY', '@r+%6h(6pu-yszhl=k)^g5@=yq8n_0xa6pd)qr=jg=+@-on&*n')

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True
DEBUG = bool(int(os.environ.get('DEBUG', default=0)))


#ALLOWED_HOSTS = ['127.0.0.1', 'localhost','192.168.0.103','192.168.1.124']

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', default='localhost').split(' ')



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cat.apps.CatConfig',
    'pars.apps.ParsConfig',
    'rest_framework'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sereja.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sereja.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.postgresql_psycopg2',
#        'NAME': 'ser_db',
#        'USER' : 'ser',
#        'PASSWORD' : '01021979a',
#        #'HOST' : '127.0.0.1',
#        'HOST' : 'db',
#        'PORT' : '5432',
#    }
#}
DATABASES = {
    "default": {
        "ENGINE": os.environ.get("SQL_ENGINE", "django.db.backends.postgresql_psycopg2"),
        "NAME": os.environ.get("SQL_DATABASE", "ser_db"),
        "USER": os.environ.get("SQL_USER", "ser"),
        "PASSWORD": os.environ.get("SQL_PASSWORD", "01021979a"),
        "HOST": os.environ.get("SQL_HOST", "localhost"),
        "PORT": os.environ.get("SQL_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Kiev'

USE_I18N = True

USE_L10N = True

USE_TZ = True

#BROKER_URL = 'redis://127.0.0.1:6379/0'
#BROKER_TRANSPORT = 'redis'
#REDIS_HOST = 'localhost'
#REDIS_PORT = '6379'
#BROKER_URL = 'redis://' + REDIS_HOST + ':' + REDIS_PORT + '/0'
#BROKER_TRANSPORT_OPTIONS = {'visibility_timeout': 3600} 
#CELERY_RESULT_BACKEND = 'redis://' + REDIS_HOST + ':' + REDIS_PORT + '/0'
#CELERY_BROKER_URL = 'redis://localhost:6379'
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER','redis://localhost:6379/0')
#CELERY_RESULT_BACKEND = 'redis://localhost:6379'
CELERY_BROKER_BACKEND = os.environ.get('CELERY_BROKER','redis://localhost:6379/0')
#app = Celery('sereja',broker='redis://localhost:6379/0', backend='redis://localhost:6379/1')
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STATIC_ROOT = os.path.join(BASE_DIR, "static")
